### ISSUE TITLE
Recursive components not rendering in production build

### ISSUE THREAD

**Issue by danpottshimself** [kaorun343/vue-property-decorator#102]
I have been having issues with recursive components only when in production builds. The issue is exactly the same as the issue below. Can anyone help?
https://forum.vuejs.org/t/recursive-component-issue-in-production-mode/35442

**Comment by kaorun343** [comment]
Hi.

Please set `name` option explicitly. Could you try this?

```ts
@Component({ name: 'YourComponent' })
class YourComponent extends Vue {}
```

**Comment by danpottshimself** [comment]
@kaorun343 worked beautifully, thank you :)

**Comment by FreezyLemon** [comment]
Small addition because I struggled with this too:

You have to explicitly set the name to whatever you used in the template of the recursive component:

```vue
<template>
  <MyComponent v-if="someCondition">
  </MyComponent>
</template>
```
requires

```typescript
@Component({
  name: 'MyComponent',
})
export default class MyComponent extends Vue {
  // ...
}
```

whereas

```vue
<template>
  <my-component v-if="someCondition">
  </my-component>
</template>
```

requires

```typescript
@Component({
  name: 'my-component',
})
export default class MyComponent extends Vue {
  // ...
}
```
