### ISSUE TITLE
@Emit with arguments from inside of component instance

### ISSUE THREAD

**Issue by vova07** [kaorun343/vue-property-decorator#103]
Hello @kaorun343 ,
First of all thank you very much for your extension.

Will try to be short.
I have a simple case when I need to `emit` an event with arguments from my `data` attribute.

Here is how it may look like in standard Vue way:
```js
methods: {
    deleteSelectedItems() {
        this.$emit('delete-selected-items', this.selected);
    }
}
```

The problem I have right now with `@Emit` decorator is because it rely only on arguments.

I think it can be solved very easy by using the return type of `original` decorator and pass that value to the emitter instead of these two lines: https://github.com/kaorun343/vue-property-decorator/blob/master/src/vue-property-decorator.ts#L116-L117

```js
var originalResult = original.apply(this, args);

if (originalResult !== false) {
    this.$emit.apply(this, [event || key].concat(originalResult));
}
```

Also as a suggestion: I think it's better to skip the emitter in case of `undefined` type in such case, just because there are much more chances that people will like to emit `boolean` values instead of `undefined`.

In case the changes will be made the emitter will look like this:
```js
@Emit()
  deleteSelectedItems(): object[] {
    return this.selected;
  }
```

Best regards,

**Comment by cybermerlin** [comment]
need close
