### ISSUE TITLE
generated JS uses type as value

### ISSUE THREAD

**Issue by doppelreim** [kaorun343/vue-property-decorator#107]
I opened https://github.com/vuejs/vue-cli/issues/1498 on `vue-cli`, but was redirected here.

Reproduction repo:
https://github.com/doppelreim/vue-test-app/tree/test-import-route

Steps to reproduce:
Run `./node_modules/.bin/vue-cli-service serve`

Expected:
The app should compile without warnings.

Actual:
There are warnings:
```
 WARNING  Compiled with 4 warnings                                                                                                            09:41:30

 warning  in ./src/components/HelloWorld.vue?vue&type=script&lang=ts

"export 'Route' was not found in 'vue-router'

 warning  in ./src/components/HelloWorld.vue?vue&type=script&lang=ts

"export 'Route' was not found in 'vue-router'

 warning  in ./src/components/HelloWorld.vue?vue&type=script&lang=ts

"export 'Route' was not found in 'vue-router'

 warning  in ./src/components/HelloWorld.vue?vue&type=script&lang=ts

"export 'Route' was not found in 'vue-router'
```

The change that introduces the warnigns can be seen here:
https://github.com/doppelreim/vue-test-app/commit/af036724ecbe53853ce10707796c82213ae07a43

I want to add a Watcher on `$route`. The parameters of the function (`newRoute` and `oldRoute`) should be typed. I assume `Route` is the correct type.

I checked out `/node_modules/vue-router/types/index.d.ts` and there `Route` does get exported, as far as I can tell.

If I use `Route` inside of the function-body, like this:
```
const r: Route = {
  path: '',
  hash: '',
  query: {},
  params: {},
  fullPath: '',
  matched: [],
};
```
then it does not throw errors.
And if I leave out some of the required attributes, then the compiler rightfully complains. So I assume the export/import does work here.

@yyx990803 provided a technical explanation in https://github.com/vuejs/vue-cli/issues/1498#issuecomment-395461425 - but there is nothing `vue-cli` can do about it.

Not sure, where to address this. Maybe here?

**Comment by lazarljubenovic** [comment]
Probably the same cause of this one as well that I ran into:

https://github.com/vuejs/vue-cli/issues/1653

Do you know where is `design:type` added? I see it being read here: https://github.com/kaorun343/vue-property-decorator/blob/master/src/vue-property-decorator.ts#L77

**Comment by KaelWD** [comment]
`design:type` is part of the decorator API: http://www.typescriptlang.org/docs/handbook/decorators.html#metadata

Specifying the correct type in the decorator options should work around this, but vue-property-decorator should really only grab valid types to use there.

**Comment by doppelreim** [comment]
Is there something I can do in my application right now to work around this issue?

**Comment by kaorun343** [comment]
Please use the new version v7.0.0.

**Comment by doppelreim** [comment]
I updated the package (see repro-repo), but the issue persists.

I am guessing - but the generated source corresponding to the one mentioned by @yyx990803 seems to be this:
```
f["b"]([Object(h["b"])(), f["e"]("design:type", String)], e.prototype, "msg", void 0),
f["b"]([Object(h["d"])("$route"), f["e"]("design:type", Function), f["e"]("design:paramtypes", ["function" === typeof (r = "undefined" !== typeof c["Route"] && c["Route"]) && r || Object, "function" === typeof (n = "undefined" !== typeof c["Route"] && c["Route"]) && n || Object]), f["e"]("design:returntype", Promise)], e.prototype, "onParamChanged", null),
e = f["b"]([h["a"]], e),
```

What other information could I provide?

**Comment by kaorun343** [comment]
Set `emitDecoratorMetadata` to `false` in your `tsconfig.json`, please.

**Comment by doppelreim** [comment]
Disabling `emitDecoratorMetadata` works. Nice!

It was initially enabled when I created the app with `vue-cli`.
Do you know whether they do it only because of `vue-property-decorator`?

**Comment by doppelreim** [comment]
Looks like it, see https://github.com/vuejs/vue-cli/blob/05391b6e9e51917437d79c46721548dc7038993a/packages/%40vue/cli-plugin-typescript/generator/template/tsconfig.json#L9

I will open an issue with `vue-cli` to remove the line from the template.

**Comment by kaorun343** [comment]
Thanks for opening the issue.

**Comment by silkentrance** [comment]
@doppelreim it exports Route as an interface in types/router.d.ts

This does not mean that you can import it as { Route } from ...

**Comment by doppelreim** [comment]
I commented on the other issue in `vue-cli` :)

How would it help if `vue-router` declared their own module?

**Comment by doppelreim** [comment]
The issue in vue-cli (https://github.com/vuejs/vue-cli/issues/1708) was resolved.
I'll close this one as well :)

**Comment by eyedean** [comment]
(Cross-ref) I found a solution with Typescript 3.8 here: https://github.com/vuejs/vue-cli/issues/1498#issuecomment-842106356
