### ISSUE TITLE
Prop type gets inferred from TS even when validator is specified

### ISSUE THREAD

**Issue by lazarljubenovic** [kaorun343/vue-property-decorator#109]
# Minimal reproduction

Writing this:

```ts
  @Prop({
    validator: (x: any) => typeof x == 'string'
  })
  public msg!: any;
```

results in runtime errors such as `Invalid prop: type check failed for prop "msg". Expected Object, got String.`. Looks like `any` is transformed into `Object` when metadata is read, and then Vue first passes the prop through custom validator and then `type: Object`.

# A more real-life scenario

The following also throws:

```ts
  @Prop({
    validator: (x: any) => x == null || typeof x == 'number'
  })
  public msg!: number | undefined | null;
```

```text
Invalid prop: type check failed for prop "msg". Expected Object, got String.
```

The reason is probably that when the type has `|`, it falls back to `Object`, which is super-wrong and super-annoying.

**Comment by lazarljubenovic** [comment]
In fact, upon further inspection, I realize that even 

```
  @Prop()
  public msg!: number | undefined | null;
```

will fail, which is pretty much not acceptable. If this module cannot figure out the type, it should not fall back to `Object`, but to simply nothing.

**Comment by lazarljubenovic** [comment]
Apparently this has been added via https://github.com/kaorun343/vue-property-decorator/pull/7. Maybe at that time only `any` caused troubles but now _everything_ other than primitive types (the `typeof` string family)` is going bananas at me. 

For now I've just copy/pasted this module and removed problematic lines and it's working like a charm to me. It would be a breaking change though for people relying on it, so I'm not sure how to approach. Ideas, suggestions, opinions?

**Comment by kaorun343** [comment]
Please use the new version `v7.0.0`.

**Comment by lazarljubenovic** [comment]
I'll be checking out tomorrow morning when I get into the office and will report back (in ~12hrs). Thanks!

**Comment by lazarljubenovic** [comment]
Yup, seems to be working fine now for me. Thanks!
