### ISSUE TITLE
@Inject example with provide ?

### ISSUE THREAD

**Issue by justinyoo** [kaorun343/vue-property-decorator#11]
Hi,

First of all, thanks for this awesome library! I wonder, if you can provide a bit more details on the `@Inject` decorator or not. I suspect this decorator is paired with the `provide` option. However, the README.md file doesn't clearly mention it.

Cheers,

**Comment by kaorun343** [comment]
Hi.

That's true -> `@Inject(provide)`. I wrote that README with referencing a Vue.js official document.

And I'll improve this README.md, thanks 😄
