### ISSUE TITLE
@Prop demo base on typescript ？

### ISSUE THREAD

**Issue by xiaofan9** [kaorun343/vue-property-decorator#112]
![image](https://user-images.githubusercontent.com/16103130/42287880-d207cbb0-7fea-11e8-84d6-9cc3f2fbc664.png)

The application of the code example to the Vue organization is directly reported. Referring to your test file, it is found that it is based on typescript and does not apply to non typescript scenarios. It is recommended to add documentation or change it to the following：

```
import { Vue, Component, Prop } from 'vue-property-decorator'

@Component
export default class YourComponent extends Vue {
  @Prop(Number) propA
  @Prop({ default: 'default value' }) propB
  @Prop([String, Boolean]) propC
}
```

**Comment by kaorun343** [comment]
This library's target is only TypeScript, not plain JavaScript. 
OK, I'll update this README. Thanks.
