### ISSUE TITLE
@Mixins How to use

### ISSUE THREAD

**Issue by savenko** [kaorun343/vue-property-decorator#113]
Hello!
I did not understand how to use new decorator @Mixins . I try use this with VeeValidate. Can you give example?

Or how to use VeeValidate with TypeScript? I can not use Vue.use(VeeValidate) because i will get computed fields for all components in projects, but i want include this plugin only for one page.

**Comment by kaorun343** [comment]
Hi.

For `@Mixins`, please check `vue-class-component` page below.
https://github.com/vuejs/vue-class-component#using-mixins

Also, I don't know how to use VeeValidate at all. Please ask to its website.

**Comment by ryanwinchester** [comment]
@savenko Did you ever figure this out? I don't know how to use it either...

**Comment by savenko** [comment]
@ryanwinchester No ((( I did this in old style

Created file 
```
// mixin.js
export default {
    methods: {
      ....
}
}
```

```
// main.ts
import mixin from './mixin.js';
Vue.mixin(mixin);
```

**Comment by kaorun343** [comment]
Could you read the document of `vue-class-component`?

**Comment by ryanwinchester** [comment]
Yeah, it did not tell me how to use `@Mixins`, either.

**Comment by kaorun343** [comment]
How about this?

https://github.com/vuejs/vue-class-component/blob/master/test/test.ts#L346

**Comment by adambullmer** [comment]
It seems like the docs here are a little misleading here. `Mixins` is in a section talking about decorators, but I found that it is not a decorator, and the docs don't prefix it with an `@`. I was able to use it with the following:

```ts
import { Component, Mixins, Vue } from 'vue-property-decorator';

@Component
class MyMixin extends Vue {
  // mixin definition here
}

@Component
class MyOtherMixin extends Vue {
  // mixin definition here
}

@Component
class MyComponent extends Mixins(MyMixin, MyOtherMixin) {
  // component definition here
}

// This also works too
@Component({
  mixins: [MyMixin, MyOtherMixin]
})
class MyOtherComponent extends Vue {
  // component definition here
}
```

I'm not certain if the mixins are supposed to be defined as a component or not, but this appears to be  working for me as is. If you start to encounter some issues in unit testing, I had to make dummy components with a defined template to consume the mixin.

**Comment by bq-hentai** [comment]
https://github.com/vuejs/vue-class-component/blob/master/test/test.ts#L389

**Comment by SanjayBanjade** [comment]
I just defined global mixin using regular `Vue.mixin`. And then do `(this as any).$_mymixin`. And I know this is not the way to go.

**Comment by baixiaoji** [comment]
I just defined global mixin using regular `Vue.mixin`.  but in vue using ts lang, the variable  in mixin, can't find and invoke compiler error 
![image](https://user-images.githubusercontent.com/21168366/60697251-0a2af980-9f1c-11e9-822d-ec5fed7115f2.png)
```
 import {Component, Mixins, Vue} from 'vue-property-decorator';
  
  @Component
  export default class Notice extends Vue {
      searchOption = {};
      noticeList = [];

      getNoticeList() {}

      handleSelectionChange(row) {
          this.selectionGroup = row;
      }
      onPaginationPageSizeChange(pageSize) {
          this.page.pageSize = pageSize;
      }
      onPaginationCurrentPageChange(currentPage) {
          this.page.pageNumber = currentPage;
      }
  }
```

**Comment by kaorun343** [comment]
@baixiaoji 
Hi.
Could you read this section of official document in order to add `page` into instance of Vue in TS world?
https://vuejs.org/v2/guide/typescript.html#Augmenting-Types-for-Use-with-Plugins

```ts
// 1. Make sure to import 'vue' before declaring augmented types
import Vue from 'vue'

// 2. Specify a file with the types you want to augment
//    Vue has the constructor type in types/vue.d.ts
declare module 'vue/types/vue' {
  // 3. Declare augmentation for Vue
  interface Vue {
    page: {
      pageSize: number
      pageNumber: number
    }
  }
}
```

**Comment by olavorn** [comment]
@kaorun343 's idea is right, but if you are using typescript declaration for typescript as class Vue modules, you need to speficy Vue declarations like this:

``` ts
declare module 'vue/types/vue' {
    // 3. Declare augmentation for Vue WITH EXPORT
    export interface Vue {
        pageSize: number // NO NEED for page
        pageNumber: number
    }
}
```
