### ISSUE TITLE
how to pass the prop from parent component to child component

### ISSUE THREAD

**Issue by wangchaoduo** [kaorun343/vue-property-decorator#115]
in my child Component , I register the prop decorator like this:
```
@Component
class Left extends Vue {
  @Prop(Boolean) public collapse!: boolean;
  public render() {
    return (
      <div>{ this.collapse }</div>
    );
  }
}
export default Left;
```
and I use this component like this:
```
<Left  collapse={ true }>
```
but the typescript can't resolve this syntax , I need to change the component file's export like this:
```
export default ( Left as any );
```
how can I pass the prop without ``export default ( Left as any );``

**Comment by kaorun343** [comment]
@wangchaoduo 

I haven't used JSX syntax yet, so could you ask this issue at Vue's official forum or Vue's discord?

**Comment by wangchaoduo** [comment]
thank you

**Comment by skyrpex** [comment]
@Magin-CC Could you get some answers? I also have this problem. It looks like the definitions for the Vue components don't have the prop information that the JSX is expecting.

**Comment by blaadje** [comment]
+1 Have this problem as well

**Comment by kaorun343** [comment]
As I wrote above,, could you ask this issue at Vue’s official forum or it’s official repository? This library isn’t related to this issue at all even if utilizing the syntax and this library together.
