### ISSUE TITLE
Using Component Injects For Prop defaults

### ISSUE THREAD

**Issue by anorborg** [kaorun343/vue-property-decorator#117]
I was attempt to replicate this following behavior from the docs [here](https://vuejs.org/v2/api/#provide-inject)

```js
const Child = {
  inject: ['foo'],
  props: {
    bar: {
      default () {
        return this.foo
      }
    }
  }
}
```

```ts
const Child = {
  @Inject({from: 'foo'})
  foo;
  @Prop({
    default () {
      return this.foo
    }
  })
  bar: string;
}
```

However, `this.foo` inside the `default` method complains:

```
Property 'foo' does not exist on type 'PropOptions<any> | Constructor | Constructor[]'
```

How can I access the injected component members in the `default` method? (Or can I?)

**Comment by kaorun343** [comment]
@anorborg 

Hi.

I wrote a new test about your issue.
Please check the test.

**Comment by tsiotska** [comment]
> @anorborg
> 
> Hi.
> 
> I wrote a new test about your issue. Please check the test.

Checked. It doesn't work. Inside default function 'this' equals null.
