### ISSUE TITLE
Wrong default prop values

### ISSUE THREAD

**Issue by jety91** [kaorun343/vue-property-decorator#118]
Something wrong with the 7.0.0 release. My `v-btn` component prop values are calculated differently in the 6.1.0 version and in the 7.0.0 version. (for example the block attribute value)

Example code:
`<v-btn :disabled="false" type="submit" variant="primary" icon="unlock-alt" block>Sign In</v-btn>`

With 6.1.0:
```
block:true
disabled:false
flat:false
icon:"unlock-alt"
loading:false
plain:false
ripple:true
to:undefined
type:"submit"
variant:"primary"
```

With 7.0.0
```
block:""
disabled:false
flat:undefined
icon:"unlock-alt"
loading:undefined
plain:undefined
ripple:true
to:undefined
type:"submit"
variant:"primary"
```

tsconfig.json
```json
{
  "compilerOptions": {
    "moduleResolution": "node",
    "module": "esnext",
    "target": "esnext",
    "sourceMap": true,
    "allowJs": true,
    "strict": true,
    "strictNullChecks": false,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": false,
    "allowSyntheticDefaultImports": true,
  }
}
```

btn.vue
```ts
@Component
export default class VBtn extends Vue {
	@Prop({
		default: "button",
	})
	public type: string;

	@Prop({
		default: "default",
	})
	public variant: string;

	@Prop({
		type: [String, Array],
	})
	public icon: string | string[];

	@Prop({
		type: [Object, String],
	})
	public to: Location | string;

	@Prop()
	public plain: boolean;

	@Prop()
	public flat: boolean;

	@Prop()
	public loading: boolean;

	@Prop()
	public block: boolean;

	@Prop()
	public disabled: boolean;

	@Prop({
		default: true,
		type: [Boolean, Object],
	})
	public ripple: boolean | object;	
}
```

**Comment by kaorun343** [comment]
@jety91 

Hi.

Do you use the same version of Vue.js?

**Comment by jety91** [comment]
Yes it's the same., vue.js@2.5.16 and vue-loader@15.2.6.

**Comment by kaorun343** [comment]
@jety91 

Since v7.0.0, it's needed to write its types explicitly like `@Prop(Boolean) plain: boolean;` or `@Prop({ type: Boolean }) plain: boolean`.
If a prop's `type` is `Boolean`, its default value is `false`.

**Comment by wedi** [comment]
I suggest throwing an error when there is no type and no default value that allows to derive the type from. I stumbled about the same thing and an error message would have been nice.
