### ISSUE TITLE
public/private/protected needed for props

### ISSUE THREAD

**Issue by ffxsam** [kaorun343/vue-property-decorator#121]
I noticed this syntax gives me a TypeScript warning in the console:

```ts
@Component
export default class Test extends Vue {
  @Prop() msg!: string;
}
```

It says:
```
WARNING in /home/samh/wat/src/components/Test.vue
10:11 The class property 'msg' must be marked either 'private', 'public', or 'protected'
     8 | @Component
     9 | export default class Test extends Vue {
  > 10 |   @Prop() msg!: string;
       |           ^
    11 | }
    12 | </script>
    13 | 
```

I noticed this isn't documented.

What's the difference between a private and public prop? It seems all props should be public.

**Comment by kaorun343** [comment]
@ffxsam 

Hi.

https://github.com/vuejs/vue-class-component/issues/94#issuecomment-408224406

According to your comment, the warning is from `tslint` . Please check your tslint configuration.
