### ISSUE TITLE
[Bug] Webpack warning about missing exported interfaces when used as @Prop type

### ISSUE THREAD

**Issue by MisterGoodcat** [kaorun343/vue-property-decorator#122]
This has been reported by user @Leandros in the vue-cli repo before (https://github.com/vuejs/vue-cli/issues/1667), but it was closed there with a comment to open an issue here. 

**Affected versions (I know of)**

vue-cli: 3.0.0-rc.3-rc.8
vue-propery-decorator: 6.2.0-7.0.0

**Steps to reproduce**

* Create new project using vue-cli + TypeScript support
* Export a TypeScript interface from a file
* Use the interface in a TypeScript component and decorate with `@Prop`
* Build or serve: `yarn serve`

Please also see the reproduction repo and steps in the linked original issue.

**Issue**

Warnings about the interface not being found in the declared file are output.

**Comment by kaorun343** [comment]
@MisterGoodcat 

Hi.

Which version of `vue-property-decorator` actually used?

If you use `v7.0.0`, then how about setting `emitDecoratorMetadata` to `false` at `tsconfig.json` ?

**Comment by MisterGoodcat** [comment]
I've upgraded to 7.0.0 today and the problem is still there.

I cannot turn off `emitDecoratorMetadata` because we're actually using reflect-metadata and rely on the info emitted by custom decorators.

**Comment by kaorun343** [comment]
I tried that I changed the option then the warning went away. 

Also, I found that there's no way currently to solve this issue.

https://github.com/Microsoft/TypeScript/issues/18008

**Comment by MisterGoodcat** [comment]
Thank you for this link. I read through the documentation and understand the underlying issue now. Unfortunately, for the last half year+ the issue only has been deferred to future milestones. Seems like we will have to live with these warnings for a another while.

**Comment by lgarczyn** [comment]
For info, this can be fixed using "import type" instead of "import"

Eslint offers `@typescript-eslint/consistent-type-import` to fix it automatically
