### ISSUE TITLE
@Watch not working when declaring components in the @component section of the vue component

### ISSUE THREAD

**Issue by tmacintosh** [kaorun343/vue-property-decorator#123]
I've have found an issue where the @Watch methods won't fire when components are declared in the @component section of the Vue  component. As below.

Not Working...

```ts
@Component({
    components: {
        Messages: require('../../../../controls/validationsummary/validationsummary.vue.html'),
    }
})
export default class NewComponent extends Vue {
     id: string = '';

     @Watch('id')
     onSelectedIdChanged(val: string) {
         doSomething(val);
     }
}
```

Working....
```ts
@Component({})
export default class NewComponent extends Vue {
     id: string = '';

     @Watch('id')
     onSelectedIdChanged(val: string) {
         doSomething(val);
     }
}
```

Is there a reason why this occurs? Or is there a work-around?

Thanks in advance.

**Comment by kaorun343** [comment]
@tmacintosh 

Hi.

The unit test of `@Watch` decorator actually passes.

Could you provide me a reproduction code?

https://github.com/kaorun343/vue-property-decorator/blob/master/test/decorator.spec.ts#L184
