### ISSUE TITLE
Publish Error using Core 2 .Net with Typescript

### ISSUE THREAD

**Issue by crtjr64** [kaorun343/vue-property-decorator#124]
My application runs fine, but when I attempt to publish it, npm install creates a new sub node_modules for vue-class-component. That component contains a declarations.d.ts file that is failing with the message:
**Version being used is: 5.3.0**
Vue only refers to a type but is being used as a namespace here. referring to this entry:

> import Vue from 'vue';
> export declare type VueClass = {
>     new (): Vue;
> } & typeof Vue;
> export declare type DecoratedClass = VueClass & {
>     __decorators__?: ((options: **Vue**.ComponentOptions<Vue>) => void)[];
> };
> 

I delete it, even move the correct copy from the main node_modules as a subfolder, but it only updates that version to replace it with the code that doesn't work. Furthermore, if I try to run the application, I get the same error until I delete the sub node folder then it goes back to running fine. But again, after I publish, it does the same thing. I ran npm outdated and all files are at its minimum requirement. I'm at the point where I may just have to bite the bullet, and rebuild the project without Typescript, webpack, npm and use VueJs with plain javaScript since there is so extremely little support for this environment and there always seem to be another hurdle where my debugging ends at someone else's code. Yes, I am frustrated.

**Comment by kaorun343** [comment]
@crtjr64 

Hi.

Could you ask this issue at `vue-class-component` ?

Its definition is defined at the library not this library.

Thanks.

**Comment by crtjr64** [comment]
The definition is from that library but the request for that library apparently comes from vue-property-decorator as a dependency, otherwise why does it install it only when I publish my app? I believe vue-property-decorator is requesting the wrong dependency file or something. I am very new to VueJs especially in this environment that seems quite out of the ordinary. I'd sincerely appreciate it if someone at least took a stab at it rather than push me off to someone else

**Comment by kaorun343** [comment]
Ah, you used an older version of this library.

How about using the latest version, v7.0.0 ?

Also, I'd like to know which version of `vue-class-component` is installed to your environment.

**Comment by crtjr64** [comment]
Version 6.2.0  of vue-class-component is installed and vue-property-decorator 5.3.0 is installed. These are considered the least required components. I want very much to install the latest but am concerned about the effect on other components and the webpack that's installed. If I go latest with vue-property-decorator will they all finally get along?

**Comment by kaorun343** [comment]
`vue-property-decorator@5.3.0` depends on `vue-class-component@^5.0.0`.

So, you need to upgrade `vue-property-decorator` to v7.0.0, which depends on `vue-class-component@^6.2.0`. 

Also, v7.0.0 works with TS 2.9.

Note that there is a breaking change in `@Prop` decorator. Since v7.0.0, it's needed to write its constructor like this if runtime checking is needed.

```ts
@Component
export default Component extends Vue {
  @Prop(Number) age!: number
}
```

**Comment by crtjr64** [comment]
That worked. Thanks a lot. Uglify broke so I had to edit tsconfig.json and reset target from "es2015" to "es5" in which I thought it already was, but whatever, its working now. Thanks again.
