### ISSUE TITLE
Need to use @component before defining class

### ISSUE THREAD

**Issue by ReevesOvO** [kaorun343/vue-property-decorator#125]
use @component before define class,it work.
![image](https://user-images.githubusercontent.com/30746521/43766631-8ce3d6e2-9a65-11e8-96b2-8d2a3e0752f9.png)
but, without @component, it doesn't work.
![image](https://user-images.githubusercontent.com/30746521/43766867-291431e2-9a66-11e8-9224-73dd5f4a9515.png)
i think it should be description in document.

**Comment by ReevesOvO** [comment]
and if i use 
@Component({})
export default {
}
an error occured. invalid ...

**Comment by kaorun343** [comment]
Could you read the README of `vue-class-component` ?
