### ISSUE TITLE
Is `el` property defining available?

### ISSUE THREAD

**Issue by TokugawaTakesi** [kaorun343/vue-property-decorator#131]
Thank you for the library.

 Unfortunately I did not find examples how to define `el` property. How can I rewrite the below code with your library?

```
var app = new Vue({
  el: '#app',
  data: {
    message: 'Hello Vue!'
  }
})
```

**Comment by kaorun343** [comment]
https://github.com/vuejs/vue-class-component/issues/268

Same to this issue.

**Comment by Taytay** [comment]
Answered here: https://forum.vuejs.org/t/is-el-property-defining-available-in-typescript-vue-property-decorator/42969/5
