### ISSUE TITLE
Emit works with promise? 

### ISSUE THREAD

**Issue by atxy2k** [kaorun343/vue-property-decorator#132]
In this moment, I'm using Emit decorator, am, and I would like to know what happend if I use something like this:
```
@Emit('deleteElement')
public deleteElement(section: Section){
     return new Promise((resolve, reject) => {
          //Something to delete 
         resolve(section);
     });  
}
```
I want to know if the decorator wait to the function ends or one way to do something similar.

**Comment by sgarciac** [comment]
> In this moment, I'm using Emit decorator, am, and I would like to know what happend if I use something like this:
> 
> ```
> @Emit('deleteElement')
> public deleteElement(section: Section){
>      return new Promise((resolve, reject) => {
>           //Something to delete 
>          resolve(section);
>      });  
> }
> ```
> I want to know if the decorator wait to the function ends or one way to do something similar.

I'm using async/await, and no, it doesn't

**Comment by atxy2k** [comment]
Thanks @sgarciac , I'll try, before, With normal vue,  I used vue-async-computed, but I think that they don't have a implementation for vue-property-decorator. 
:(

**Comment by kaorun343** [comment]
@atxy2k @sgarciac 

Hi.

Could you use the latest version (7.2.0) ?
I implemented this feature.

**Comment by atxy2k** [comment]
Oh! that's great! I gonna upgrade!, thanks.
