### ISSUE TITLE
UMD build is missing in 7.1.0

### ISSUE THREAD

**Issue by hwestphal** [kaorun343/vue-property-decorator#138]
When installing `vue-property-decorator@7.1.0`, the UMD build of the library is missing (`lib/vue-property-decorator.umd.js`).

### How to reproduce ###
```
$ npm i vue vue-property-decorator@7.1.0
$ node -e 'require("vue-property-decorator")'
...
Error: Cannot find module 'vue-property-decorator'
...
```

**Comment by kaorun343** [comment]
@hwestphal 

Thanks.
