### ISSUE TITLE
@Watch：the new values the same as the old ones

### ISSUE THREAD

**Issue by superliyy** [kaorun343/vue-property-decorator#140]
Hi, you are too good, but I found a problem，as follows：

```ts
@Watch('form', { immediate: true, deep: true })
  onFormChanged(newVal, oldVal) {
    console.log(JSON.stringify(newVal), JSON.stringify(oldVal)) 
    /*****{"password":"123456"} {"password":"123456"}*******/
  }
```

Why are the new values the same as the old ones? Unscientific！Looking forward to your reply！Thank you！

**Comment by kaorun343** [comment]
@superliyy 

Hi.

Could you try this code ?

```ts
console.log(newVal === oldVal)
```

**Comment by superliyy** [comment]
Hi,
Results are as follows：
/***{"password":"12"} {"password":"12"}***/
/*** true***/
