### ISSUE TITLE
How to get data from Emit

### ISSUE THREAD

**Issue by romanmarkelov** [kaorun343/vue-property-decorator#143]
```html
<input
        :value="value"
        :checked="shouldBeChecked"
        type="checkbox"
        @change="updateInput"
>
```

```js
@Emit('change')
  updateInput(event) {
    const isChecked = event.target.checked;

    if (this.modelValue instanceof Array) {
      const newValue = [...this.modelValue];

      if (isChecked) {
        newValue.push(this.value);
      } else {
        newValue.splice(newValue.indexOf(this.value), 1);
      }
      return newValue;
    }
    return isChecked ? this.trueValue : this.falseValue;
  }
```
I getting an event. How to get data?

**Comment by foxbunny** [comment]
The documentation says:

> The functions decorated by `@Emit` `$emit` *their arguments* after they ran. (italics mine)

So the behavior is intended. To be honest, I don't really use this pattern in my apps, so not 100% sure, but I would say it's not the most useful implementation. I would probably expect the return value of the method to be `$emit`ed had I not read the docs just now.

**Comment by foxbunny** [comment]
Oh, ok, apparently, the [code on the master](https://github.com/kaorun343/vue-property-decorator/blob/83b6100c4fad553d49a86a3c1abc379c0160bf89/src/vue-property-decorator.ts#L101-L122) *does* emit the return value, and even resolves promises for async functions. Best wait for the next release then, or use the version on the master branch.

**Comment by foxbunny** [comment]
Oh, ok, apparently, the [code on the master](https://github.com/kaorun343/vue-property-decorator/blob/83b6100c4fad553d49a86a3c1abc379c0160bf89/src/vue-property-decorator.ts#L101-L122) *does* emit the return value, and even resolves promises for async functions. Best wait for the next release then, or use the version on the master branch.

**Comment by eddow** [comment]
I opened a [discussion](https://github.com/kaorun343/vue-property-decorator/issues/146) about it - it seems that `@Emits` went wild since it was written and it should be decided how to handle it correctly - it is quite changing every month.
