### ISSUE TITLE
How to use it with vuex-persistedstate

### ISSUE THREAD

**Issue by Sodininkas** [kaorun343/vue-property-decorator#145]
Hello,

Whit all tests, state is save to local storage, but object never gets values, what is the issue here? Maybe there are some alternatives, examples to save state in local/cookie storage

**Comment by kaorun343** [comment]
@Sodininkas 

Hi.

Could you open your issue at `vuex-persistedstate` ?
It seems that your issue isn't related to `vue-property-decorator`.
