### ISSUE TITLE
Help! @Watch can not watch '$router' in Typecript

### ISSUE THREAD

**Issue by CloseGillter47** [kaorun343/vue-property-decorator#147]
```
  @Watch('id')
  public getLinksFromRoute (val: any, old: any) {
     console.log(1); // worked
  }
```
```
  @Watch('$route')
  public getLinksFromRoute (val: Route, old: Route) {
     console.log(1); // not worked
  }
```

**Comment by avinograd0v** [comment]
it also doesn't work in normal JS

**Comment by foxbunny** [comment]
Is `$route` reactive to begin with?

**Comment by Nicholas-Westley** [comment]
@CloseGillter47  It works if 'deep' is set to true.
`@Watch('$route', {deep: true})`

@foxbunny What is recommended way to react to route changes?

**Comment by foxbunny** [comment]
@Nicholas-Westley It depends on the router implementation, so I can't give you a canned answer. For my projects, I just use a generic event system so I can hook anything up to it, including `hashchange` and any application-initiated route changes. (Shameless plug:) [Here](https://codeburst.io/client-side-routing-done-right-3464275778bf) are some details if you want to learn more.

**Comment by CloseGillter47** [comment]
@Nicholas-Westley nice and thanks!

**Comment by jordanboston** [comment]
@Nicholas-Westley this does not seem to work for me even with deep:true.

Anything else I might be missing?

 ```
 @Watch('$route', { deep: true })
  onRouteChange (to: any, from: any) {
    console.log(to)
    this.photoId = to.params.id
  }
```

**Comment by loferreiranuno** [comment]
@Watch('$route', { immediate: true, deep: true }
)
 onRouteChange (to: any, from: any) {
   console.log(to)
   this.photoId = to.params.id
 }

**Comment by mathmul** [comment]
Not working for me either.

Vue 2.6
```js
import { Component, Vue, Watch } from 'vue-property-decorator';
...
    @Watch('$route', { immediate: true, deep: true })
    private log() {
        console.log('never called');
    }
```

1. I load URL "localhost/?orderNumber=123".
2. On `mounted()` the input field with value `this.model.orderNumber` gets filled with `this.$route.query.orderNumber` and then it's submitted
3. On submit  it updates URL and pushes to history with the following
```js
    // I tried to put @Watch before the function wrapping this
    const url = new URL(window.location.href);
    url.searchParams.set('orderNumber', this.model.orderNumber.toString());
    window.history.pushState({}, '', url.toString());
```
4. Then I change orderNumber to 321 via the input (from 2.) and 3. is executed again.
5. Now if I press "back" in Chrome it only goes back with URL, but the input or anything else on page.

Funnily enough, if I go through steps 1. to 4. and then I change the orderNumber again to let's say 456, "back" works once, but the second time it again doesn't.
