### ISSUE TITLE
[feature request] @Watch multiple properties.

### ISSUE THREAD

**Issue by wujekbogdan** [kaorun343/vue-property-decorator#148]
It would be great if we could do:

``` javascript
  @Watch([
    'prop1',
    'prop2',
  ])
  handler() {
    // Do something
  }
```

**Comment by foxbunny** [comment]
@wujekbogdan This should be a feature request for Vue.js not this library.

**Comment by runxc1** [comment]
So this is actually something that you can do already do in vue.js and it looks like there are a couple different ways to do it.

Below is the discussion on the exact feature request to Vue.js
https://github.com/vuejs/vue/issues/844#issuecomment-335026928

It looks like the most document way is to use a function to watch more than one property.
https://vuejs.org/v2/api/#vm-watch shows the following example

```
vm.$watch(
  function () {
    return this.a + this.b
  },
  function (newVal, oldVal) {
    // do something
  }
)
```

It would be nice to be able to do something like

 ```
@Watch(function () {
    return this.a + this.b
  }, "myHandler")
  myHandler(newVal, oldVal) {
    // Do something
  }

```

**Comment by Alendorff** [comment]
So what is the way to watch for two props with single function? In common vue we can pass handler option to watcher config.

**Comment by kaorun343** [comment]
You’re right.

**Comment by Alendorff** [comment]
Okay, thank you, I'll recheck it later.

**Comment by philiprenich** [comment]
Seems like this shouldn't be closed. Vue.js allows specifying a handler (as a string) so that you can re-use the same method for different watched props. Having this in @Watch would be nice as well, whether it was in the `WatchOptions` as `handler` (parity with Vue.js) or as a decorated entity in some form (how @kaorun343 specified or otherwise)
