### ISSUE TITLE
What about @Mixin?

### ISSUE THREAD

**Issue by lucastheisen** [kaorun343/vue-property-decorator#15]
Not quite sure how just yet, but it would be really nice to have an `@Mixin`.  Something analagous to `@Component`.  That way you could write something like:

```
import { Mixin, Prop } from 'vue-property-decorator';

import BarComponent from 'app/components/bar-component.vue';
import BazMixin from 'app/mixins/baz-mixin.ts';

@Mixin({
    components: {
        BarComponent
    }
    mixins: {
        BazMixin
    }
})
export default class FooMixin {
    @Prop() public propOne: string;
    public dataOne: string;
    public dataTwo: boolean;

    public created() {
        console.log("hooked into created in FooMixin");
    }

    public methodOne(): void {
        // do stuff
    }
}
```

What do you think?

**Comment by kaorun343** [comment]
All of Vue components can be mixin, so It's not needed, I think.

https://github.com/vuejs/vue/blob/dev/types/options.d.ts#L53

**Comment by lucastheisen** [comment]
@kaorun343 are you saying i should just use an `@Component` then?  Something like:

```
import { Component } from 'vue-property-decorator';

import BarComponent from 'app/components/bar-component.vue';
import BazMixin from 'app/mixins/baz-mixin.ts';

@Component({
    components: {
        BarComponent
    }
    mixins: {
        BazMixin
    }
})
export default class FooMixin {
    @Prop() public propOne: string;
    public dataOne: string;
    public dataTwo: boolean;

    public created() {
        console.log("hooked into created in FooMixin");
    }

    public methodOne(): void {
        // do stuff
    }
}
```

Then use it in a component:

```
<template>
  <span>{{ propOne }}</span><span>{{ dataOne }}</span>
</template>
<script lang="ts">
import { Component } from 'vue-property-decorator';

import FooMixin from 'app/mixins/foo-mixin.ts';

@Component({
    mixins: {
        FooMixin
    }
})
export default class FooMixin {
    doLotsaStuff() {
        this.methodOne();
    }
}
</script>
```

Even if that does work, it still seems like it would be valuable to have the `@Mixin` decorator as an alias because it would clarify the use case...  What do you think?

**Comment by kaorun343** [comment]
Then, you can do like this below to imply that the component is a mixin explicitly.

```ts
import { Component as Mixin } from 'vue-property-decorator'
// or
import Mixin from 'vue-class-component'

@Mixin({
    components: {
        BarComponent
    }
    mixins: {
        BazMixin
    }
})
export default class FooMixin {
    @Prop() public propOne: string;
    public dataOne: string;
    public dataTwo: boolean;

    public created() {
        console.log("hooked into created in FooMixin");
    }

    public methodOne(): void {
        // do stuff
    }
}
```

**Comment by lucastheisen** [comment]
Excellent point...  That completely passed through my mind.  Thanks.

**Comment by thasmo** [comment]
@kaorun343 This seems legit, although the `Component` decorator always sets the `name` property, I guess, so using a Mixin named `Component`, or `Button` will fail because `Vue` doesn't like component names which clash with default HTML element names. Is there a workaround for this?

**Comment by kaorun343** [comment]
@thasmo 

Hi.
Please see this link below. If you add `name` option into `@Component`, it'll be a component name.

```typescript
@Component({ name: 'button-mixin' })
export default class Button {}
```

https://github.com/vuejs/vue-class-component/blob/master/src/component.ts#L29

**Comment by thasmo** [comment]
Thanks! Wouldn't it be nice to have a `@Mixin` decorator which does **not** set the `name` property or do you think explicitely defining a name is the better way?
