### ISSUE TITLE
Suggestion: @Prop uses TS for type and default

### ISSUE THREAD

**Issue by sp33dlink** [kaorun343/vue-property-decorator#154]
Currently we have to write:
`@Prop({type: Number, default: 1) some!: number`.

It would be way more logical and readable to just infer type and default from it's value.
`@Prop() some: number = 1`

I know that you don't have to specify the types if you assign a value right away. Isn't it possible to get the value and type and pass them to vue?
Currently we don't even get a warning if we pass a String to that property if it's not specified in the annotations type.
I assumed that exactly this was the argument to go for typescript.

**Comment by foxbunny** [comment]
I don't think that's technically doable. TS types are not available at runtime, and type checking in `@Prop()` is a runtime thing.

**Comment by foxbunny** [comment]
> And for the default value i can see an optional setting as well.

Problem is that not everyone uses runtime type checking in props. So if you add a default, then people's app may break.

**Comment by sp33dlink** [comment]
That's the reason I suggested an optional setting which is off by default.

**Comment by foxbunny** [comment]
I think it's simpler to write your own `@Prop` decorator that does what you need.

**Comment by foxbunny** [comment]
Here, the Prop decorator is just three lines:

```typescript
export function Prop(options: (PropOptions | Constructor[] | Constructor) = {}): PropertyDecorator {
  return createDecorator((componentOptions, k) => {
    (componentOptions.props || (componentOptions.props = {}) as any)[k] = options
  })
}
```

All you need to do is make sure there is a `type` property in the `options`.

**Comment by eddow** [comment]
I don't know why, but we can see [here](https://github.com/kaorun343/vue-property-decorator/commit/1d2f34130d174c9b504f3912f9c6f3f28f8d1d92) that this functionality was implemented and removed - I don't really know why. I noticed when I thought about upgrading my version of `vue-property-decorator` that I had to inflate my decorators.

I indeed prefer the older version of `vue-property-decorator` but I now have to upgrade to comply to some products :-/

**Comment by foxbunny** [comment]
Because `undefined` is the default in Vue.

**Comment by eddow** [comment]
Was that an answer to my message ? I don't really understand...

**Comment by foxbunny** [comment]
To this, sorry, forgot to quote.

> I don't know why, but we can see here that this functionality was implemented and removed - I don't really know why.

**Comment by foxbunny** [comment]
The way I understand it, `vue-property-decorator` is not meant to *add* functionality to Vue, but to provide an interface to use what Vue has. Therefore, setting a default that's different from what Vue uses is wrong in that respect. Whether you like the Vue's default is an orthogonal issue, and easily solved using a custom decorator.

**Comment by armano2** [comment]
@eddow there is way to do so, we will have to handle it at compilation level, eg. babel plugin.

**Comment by foxbunny** [comment]
> Also, about custom decorators, I'd be interested in easy ways as, beside re-writing another "vue-property-decorator" library or implementing these decorators in each projects I have that use the library, I see no clean way to do it.

It's not my call, so feel free to disregard, but:

1. You don't need to rewrite vue-property-decorator to have a `@Prop` with the default of your choosing. I have a bunch of decorators of my own that I maintain separately and I haven't noticed any issue with that. They don't even depend on `vue-property-decorator` because that's not the package that contains the low-level factory function.
2. Even rewriting `vue-property-decorator` is not exactly hard, as it's merely a collection of decorators that uses `vue-class-component` under the hood.
3. You can also fork it and merge changes from upstream from time to time.

**Comment by eddow** [comment]
@armano2 "we" ? I don't think this "setting the type to reflexion metadata" would fit somewhere else than in `vue-property-decorator` - or for instance, the babel-plugin would have to have knowledge of the `@Prop` decorator I think

@foxbunny As we were not really speaking about changing the default type, but looking up the typescript type in order to infer the property type, it's more complex than just overriding a devault value.
The old code of `vue-property-decorator` that was doing the job was this :
```ts
export function Prop(options: (PropOptions | Constructor[] | Constructor) = {}): PropertyDecorator {	 export function Prop(options: (PropOptions | Constructor[] | Constructor) = {}): PropertyDecorator {
   return function (target: Vue, key: string) {	   return createDecorator((componentOptions, k) => {
     if (!Array.isArray(options) && typeof (options as PropOptions).type === 'undefined') {	     (componentOptions.props || (componentOptions.props = {}) as any)[k] = options
       (options as PropOptions).type = Reflect.getMetadata('design:type', target, key)	   })
     }	
     createDecorator((componentOptions, k) => {	
       (componentOptions.props || (componentOptions.props = {}) as any)[k] = options	
     })(target, key)	
   }	
 }
```

Also, sure, re-doing vue-property-decorator is not a fuss (I did even add some functionalities to `vue-property-decorator` myself) It is just that it would be silly to have an npm package named `vue-property-decorator2`

**Comment by foxbunny** [comment]
@eddow sorry, I didn't realize you were still talking about that. No, that's not possible and the old code was not doing that.

https://stackoverflow.com/questions/44078205/how-to-check-the-object-type-on-runtime-in-typescript

**Comment by foxbunny** [comment]
Your best bet is what @armano2 suggests, and that is outside the scope of this project for sure.

**Comment by eddow** [comment]
@foxbunny The old code was doing it - upgrading this library was a pain in the a*se for me as the old one was making the job and the new one didn't.

**Comment by foxbunny** [comment]
> The old code was doing it

Could you explain how it does it? Because you know... it would mean that it's doing something that's impossible to do.

**Comment by eddow** [comment]
Well, it is using the library `reflect-metadata`.
Even without the library, the typescript transpiler decorates the properties. For example, I take a small transpilation:

Typescript:
```ts
	@Prop({default: '/'}) emptyRoute: string
```
Becomes in javascript:
```js
    __decorate([
        vue_property_decorator_1.Prop({ default: '/' }),
        __metadata("design:type", String)
    ], glRouter.prototype, "emptyRoute", void 0);
```
Again, you can see how the `Prop` function changed [here](https://github.com/kaorun343/vue-property-decorator/commit/1d2f34130d174c9b504f3912f9c6f3f28f8d1d92) : it used `Reflect.getMetadata('design:type', target, key)` when the type was not defined

**Comment by foxbunny** [comment]
@eddow Wow, that's is nuts! I'm actually 200% more glad I left TypeScript. It creates problems that you have to solve instead of solving problems you already have. OMG.

**Comment by sunyatasattva** [comment]
Any news about this issue from the maintainer @kaorun343 ? I'd +1 both OP and @eddow here. It seems wasteful, duplicated and error-prone to do something like:

```ts
@Prop({ default: 'default', type: String }) myProperty: string = 'default';
```

when this is much more succinct and meaningful:

```ts
@Prop() myProperty: string = 'default';
```

And the desired output would be something like:

```js
props: {
    myProperty: {
      type: String,
      default: 'default'
    }
  }
```

**Comment by eddow** [comment]
@sunyatasattva Well, indeed the `... = 'default';` is illegal as properties cannot be affected. Though - this gave me an idea, this is perhaps possible to use this to specify the default, that would feel more natural.

I'll perhaps try to PR about it, though we had no answer from @kaorun343 and it seems that functionality was removed with the `reflect-metadata` dependence. If that dependency issue was the purpose, it's perhaps useless to bring it back as it would be refused.

A feedback from @kaorun343 would definitely help.

**Comment by sunyatasattva** [comment]
Thanks for your fast reply @eddow.

For me the whole point of both decorators and TypeScript, is to make the code more readable and maintainable. Vue already allowing to define types for properties even without TypeScript was always an appreciated feature from me.

But now we have to duplicate code and make it unnecessarily more verbose.

**Comment by kaorun343** [comment]
Hi. I apologize you for late reply...

About taking a default value as an instance property, it's difficult to solve by changing only this library (which means it's needed to change `vue-class-component`, too), and I won't support it.

https://github.com/kaorun343/vue-property-decorator/issues/5
https://github.com/vuejs/vue-class-component/issues/60
https://github.com/vuejs/vue-class-component/pull/62

About setting a `type` property with `reflect-metadata`, I stopped doing it by several reasons: 

* https://github.com/kaorun343/vue-property-decorator/issues/107
* Props' type checking is done in development environment only, and for only developing, type inference is not needed, I think.

**Comment by sunyatasattva** [comment]
@kaorun343 さん返事をくれて、ありがとうございました！

The threads you have linked mention that it is possible to work around this issue to achieve the desired result using a decorator factory. But it's not clear to me how; would it be too much to ask to elaborate on that aspect?

**Comment by foxbunny** [comment]
@sunyatasattva Specifically, you want to look at [this part of the README](https://github.com/vuejs/vue-class-component#create-custom-decorators) in the vue-class-component project. Or you could locate the version of `@Prop()` in this library that was doing what you want, and extracting that into a separate module. I believe @eddow mentioned it in the comments.

**Comment by eddow** [comment]
Really, I have now to go through all my old project and replace `@Prop() myVar: boolean` with `@Prop({type: Boolean}) myVar: boolean` because this functionality has been *removed*.

I really cannot wrap my head around why this is a feature - all my libs have to be refactored.

**Comment by clementmas** [comment]
@kaorun343 what's your take on the latest comments?

> But now we have to duplicate code and make it unnecessarily more verbose.

Completely agree with this

**Comment by kaorun343** [comment]
I will support `reflect-metadata` again.

**Comment by kaorun343** [comment]
Please check the latest version, `v8.1.0`.
