### ISSUE TITLE
Small typo in @Prop example in README

### ISSUE THREAD

**Issue by philipchungtech** [kaorun343/vue-property-decorator#158]
The `propC` property should have a non-null assertion operator `!` like the others.

**Comment by kaorun343** [comment]
@philipchungtech 

Hi.

Thanks. I've fixed this.

**Comment by Alendorff** [comment]
@kaorun343 I think it worth mention the meaning of this operator in readme, could be confusing for those who switching on ts in their projects. It looks confusing at the first look and a bit hard to google what does it mean in ts.
