### ISSUE TITLE
how to use @Emit for multiple parameters

### ISSUE THREAD

**Issue by yunweb** [kaorun343/vue-property-decorator#161]
for example：
`
@Emit('reset')
returnMultipleValue() {
        return a, b, c;
}

/*****equivalent to*****/

this.$emit('reset', a, b, c);
`
And I can receive multiple parameters。

**Comment by jacobrabjohns** [comment]
Make a single object containing those parameters? 

@emit('reset')
returnMultipleValue() {
return {a, b, c};
}

**Comment by foxbunny** [comment]
@yunweb 

`return a, b, c;` is not legal JavaScript. Normally, JavaScript parsers (including TypeScript) would throw a syntax error right there. What @jacobrabjohns suggests is the best way to do it.

Personally, I think it's cleaner to just use `this.$emit()` anyway. It makes it clearer about when exactly it is going to be called and with what arguments, and decouples the implementation of your method from the stuff you want to emit. But that's just me.

**Comment by yunweb** [comment]
> Make a single object containing those parameters?
> 
> @emit('reset')
> returnMultipleValue() {
> return {a, b, c};
> }

But this is one parameters

**Comment by foxbunny** [comment]
There is no way to return multiple values from a function in JavaScript/TypeScript (and most languages for that matter).

**Comment by Kingwl** [comment]
@foxbunny 
> return a, b, c; is not legal JavaScript

why that (comma expression) is not legal js?
