### ISSUE TITLE
Mixins limit?

### ISSUE THREAD

**Issue by mailok** [kaorun343/vue-property-decorator#163]
Hello, I was using Mixins and apparently there is a mixin limit that I can use

![error](https://user-images.githubusercontent.com/3769277/50837398-88219580-1329-11e9-8ca1-bb03e4471f33.png)

but when I leave only 5 mixin I do not get an error:

![no error](https://user-images.githubusercontent.com/3769277/50837459-aab3ae80-1329-11e9-9ccc-51d48fe1c958.PNG)

This is a bug?

**Comment by kaorun343** [comment]
@mailok 

Hi.

The Mixin function supports up to 5 arguments.

https://github.com/vuejs/vue-class-component/blob/master/src/util.ts#L35

**Comment by kyusupov33** [comment]
@kaorun343 what should I do if I want to use more than 5 Mixins?

**Comment by phil-w** [comment]
If we're claiming this as a feature I believe it's traditional to document it. I suppose this just about counts ;-)

The annoying thing about this one is that it doesn't tell you that it's a limit, so you have to work it out. Solutions are not really an issue for here... refactor the code so it uses 5 or fewer.

**Comment by cereschen** [comment]
As many as you want
```ts
@Component
export default class extends Mixins(Mixins(Mixin2,Mixin2,Mixin2,Mixin2,Mixin2),Mixins(Mixin1,Mixin1,Mixin1,Mixin1,Mixin1)){
}
```

**Comment by LaivlyCurt** [comment]
> @mailok
> 
> Hi.
> 
> The Mixin function supports up to 5 arguments.
> 
> https://github.com/vuejs/vue-class-component/blob/master/src/util.ts#L35

Can this be reopened now that we have these please? https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#variadic-tuple-types
