### ISSUE TITLE
Is there any way to change a prop?

### ISSUE THREAD

**Issue by NE-SmallTown** [kaorun343/vue-property-decorator#166]
I'm using the `@Props` decorator but find that I can't get the real value of a prop, for example:

```
@Component
export default class MyComponent extends Vue {
  @PlusOne
  @Prop(Number) foo!: number
}
```

Here `PlusOne` is created by `createDecorator` or just a normal decorator function, but both them can't access/change the `foo` prop(I tried `target.foo`, `target.$data`, `target.$props` but all of them are `undefined`), so, I can't make the `foo` + 1

Is there any way to solve this?

**Comment by kaorun343** [comment]
@NE-SmallTown 

Hi.

There's no way to change a prop from child component.

**Comment by NE-SmallTown** [comment]
Could this repo provide some hooks to do this?

**Comment by kaorun343** [comment]
This library is just like a syntax sugar for Vue and TS users. So, I’d like you to create the example utilizing `Vue.extend({})`. If there’s any features to make writing it better, I’ll add into this library.
