### ISSUE TITLE
How do you achieve nested computed variables if you are using namespaced modules in your vuex store?

### ISSUE THREAD

**Issue by jacklp** [kaorun343/vue-property-decorator#173]
How do you achieve nested computed variables if you are using namespaced modules in your vuex store?

> As mentioned in [this tutorial](https://alligator.io/vuejs/typescript-class-components/), computed properties are implemented in vue-property-decorator as ES6 getters:
> ```javascript
> @Component
> export default class App extends Vue {
>   get myComputedProp() {
>     return Math.random()
>   }
> }
> ```
> Which is equal to this plain Vue syntax:
> ```javascript
> export default {
>   computed: {
>     myComputedProp() {
>       return Math.random()
>     }
>   }
> }
> ```
> 
> _Originally posted by @ninjascant in https://github.com/kaorun343/vue-property-decorator/issues/85#issuecomment-370366461_

**Comment by Serhansolo** [comment]
I bump this! :)

**Comment by bodograumann** [comment]
Does this belong to https://github.com/championswimmer/vuex-module-decorators?

**Comment by kaorun343** [comment]
Could you describe what you'd like to achieve by using `Vue.extend({})` ?
