### ISSUE TITLE
tsx support

### ISSUE THREAD

**Issue by romanmarkelov** [kaorun343/vue-property-decorator#175]
-   Laravel Mix Version: 4.0.14
-   NPM Version 6.5.0
-   OS: macOS 

### Description:
"[Vue warn]: Failed to mount component: template or render function not defined."
### Steps To Reproduce:
clone [repo](https://github.com/romanmarkelov/example-laravel-mix-tsx) 
`run yarn &&  yarn hot`

open browser console: "[Vue warn]: Failed to mount component: template or render function not defined."

**Comment by skyrpex** [comment]
Can I ask why did you close this issue? I wanted to ask about render functions and saw this issue.

**Comment by romanmarkelov** [comment]
See [here](https://github.com/JeffreyWay/laravel-mix/issues/2008)

**Comment by skyrpex** [comment]
Thanks!
