### ISSUE TITLE
Attribute Not Support

### ISSUE THREAD

**Issue by xyjwsj** [kaorun343/vue-property-decorator#182]
vue code:
export default {
    layout: 'xxxx'
}

I use Ts code:
export default class extends Vue {
   ？？？？
}

TS does not have this way of writing！

**Comment by yarkovaleksei** [comment]
Code
```typescript
export default class extends Vue {
    layout:string = 'xxxx'
}
```
equal to
```javascript
export default {
    data () {
        return {
            layout: 'xxxx'
        }
    }
}
```

**Comment by xyjwsj** [comment]
> Code
> 
> ```ts
> export default class extends Vue {
>     layout:string = 'xxxx'
> }
> ```
> 
> equal to
> 
> ```js
> export default {
>     data () {
>         return {
>             layout: 'xxxx'
>         }
>     }
> }
> ```

TS does not have this way of writing

**Comment by kaorun343** [comment]
@xyjwsj 

Hi. 

This is written in the document of `vue-class-component`.

```ts
@Component({ layout: 'xxxx' })
class YourComponent extends Vue {}
```

**Comment by kaorun343** [comment]
https://github.com/vuejs/vue-class-component#usage

**Comment by xyjwsj** [comment]
> https://github.com/vuejs/vue-class-component#usage

yeah, It's right. Thanks

**Comment by yarkovaleksei** [comment]
> TS does not have this way of writing

Yes, of course)) I meant that the record is equivalent to a JavaScript expression.

**Comment by ryanwinchester** [comment]
@kaorun343 

```
Argument of type '{ layout: string; components: { Card: typeof Card; }; }' is not
assignable to parameter of type 'VueClass<Vue>'.

Object literal may only specify known properties, and 'layout' does not exist
in type 'VueClass<Vue>'.
```

**Comment by kaorun343** [comment]
https://vuejs.org/v2/guide/typescript.html#Augmenting-Types-for-Use-with-Plugins

Please refer to this section.

**Comment by kaorun343** [comment]
You need to add `display` into `ComponentOptions` .
