### ISSUE TITLE
Prop Use Error

### ISSUE THREAD

**Issue by xyjwsj** [kaorun343/vue-property-decorator#183]
Compile error with @prop project, error message ( Decorating class property failed. Please ensure that proposal-class-properties is enabled and set to use loose mode. To use proposal-class-properties in spec mode with decorators, wait for the next major version of decorators in stage 2. )

This is my code:

```js
export default class Wrap extends Vue {
    @Prop() nextBtn
}

```
use:  <Wrap @nextPage="toNextPage" :nextBtn="next">

**Comment by clementmas** [comment]
Duplicate #142
