### ISSUE TITLE
Mixins type incompatibility when extending from component

### ISSUE THREAD

**Issue by terrymun** [kaorun343/vue-property-decorator#189]
Based on how I understood how Mixins in VueJS work, when extending a new VueJS component from a pre-existing mixin defined properties and methods should be overridden should it be specified. In other words, the[ component's properties/methods will take priority](https://vuejs.org/v2/guide/mixins.html#Option-Merging) over that of mixins in case of key clashes.

However, I find that this is not the case how typings are made for vue-property-decorator. Given the following mixin, which is a generic mixin used by all `<input>`-like elements:

```ts
// _baseInput.mixin.vue
import { Component, Emit, Prop, Vue } from 'vue-property-decorator';

@Component({
  name: 'baseInput'
})
export default class BaseInput extends Vue {
    public $el!: HTMLInputElement;

    @Prop({ type: String })
    public readonly value!: string;

    @Emit('change')
    public onInput(): string {
        return this.$el.value;
    }
};
```

And it's extended by say, an input component that only accepts numbers:

```ts
// numericInput.vue
import { Component, Emit, Mixins, Prop } from 'vue-property-decorator';
import BaseInput from './_baseInput.mixin.vue';

@Component({
  name: 'numericInput'
})
export default class NumericInput extends Mixins(BaseInput) {
    @Prop({ type: Number })
    public readonly value!: number;

    @Emit('change')
    public onInput(): number{
        return +this.$el.value;
    }
}
```

I actually get an error, since the prop `value` in the mixin only accepts `string` and is now incompatible with the component's own prop` value` which is `number`.

![Code_2019-03-28_07-42-41](https://user-images.githubusercontent.com/5593067/55135894-2e14bd00-512d-11e9-8cf5-c3d8060e9015.png)

Likewise, the same type incompatibility warning is thrown of the `onInput()` method:

![Code_2019-03-28_07-43-43](https://user-images.githubusercontent.com/5593067/55135911-3bca4280-512d-11e9-9d8f-14f6914c5962.png)

Based on what I understood, the `value` prop and `onInput()` methods should have their types overwritten in the `NumericInput` component since its typings and definitions precedes that of the mixin's.

**Comment by kaorun343** [comment]
@terrymun 

Hi.

This is a TypeScript's normal behavior. As shown in this screenshot, its type checking works as same as your code.

<img width="620" alt="スクリーンショット 2019-03-28 15 47 46" src="https://user-images.githubusercontent.com/5625395/55136128-e879e380-5170-11e9-934e-2865221e5c18.png">

**Comment by terrymun** [comment]
My question is that this shouldn't be the default behavior, IMHO. I see mixins as ES6 classes whose members can be overridden (including their types and return types). VueJS itself is very unopiniated in this sense, so I wonder if this is actually expected behavior.
