### ISSUE TITLE
How to set Prop type and object

### ISSUE THREAD

**Issue by senner007** [kaorun343/vue-property-decorator#191]
How so I set a type (Number) and an object in the Prop function ?
``
  @Prop(Number, {default : 0}) SelectedFeedbackFlowId : number  // not working!
``

**Comment by yarkovaleksei** [comment]
Try this:
```typescript
@Prop({type: Number, default : 0}) SelectedFeedbackFlowId: number;
```

**Comment by senner007** [comment]
hmm. I thought I had already tried this. But it's working! Thanks for the the quick reply

**Comment by yarkovaleksei** [comment]
It's my pleasure ))
