### ISSUE TITLE
Extend @component to add support of template & style

### ISSUE THREAD

**Issue by oliviermattei** [kaorun343/vue-property-decorator#192]
I worked with angular and I just see the work of [foreverzmy/vue-ts-componet](https://github.com/foreverzmy/vue-ts-componet).

It should be wonderful to make it possible with `vue-property-decorator` and being a well maintenained feature.

It is a hole in the racket and is essentially the only thing missing and makes the use of class component unsuccessful.

**Comment by kaorun343** [comment]
@oliviermattei 

Hi.

Currently using `template` is supported as Vue itself supports it, whereas `style` and `scope` aren't supported. There's no plan to support these CSS related properties as `Vue.extend` doesn't support them.

Thanks.
