### ISSUE TITLE
Cannot find module 'vue-property-decorator'

### ISSUE THREAD

**Issue by baixiaoji** [kaorun343/vue-property-decorator#199]
I install the `vue-property-decorator@8`, and run the project  but the terminal can't find the declare file in lib file.
I search typescript config file and add the types config , it didn't work.
typescript@3.4.5   vue@2.5.22
```json
// my tsconfig.json
{
  "include": [
    "./src/**/*"
  ],
  "exclude": [
    "node_modules"
  ],
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "allowJs": true,
    "module": "es2015",
    "target": "es5",
    "moduleResolution": "node",
    "isolatedModules": true,
    "lib": [
      "dom",
      "es5",
      "es6",
      "es7",
      "es2015.promise"
    ],
    "sourceMap": true,
    "pretty": true,
    "strict": true 
  }
}

```

**Comment by jericomanapsal** [comment]
Since it can't find the file, maybe it's not yet installed on `node_modules`? Try `npm install` or `yarn install`.

**Comment by baixiaoji** [comment]
> Since it can't find the file, maybe it's not yet installed on `node_modules`? Try `npm install` or `yarn install`.

I have installed it, but i change entry file to ts file, it solved

**Comment by Mouradif** [comment]
What was the fix? I have this warning in my IDE too
