### ISSUE TITLE
@watch doesn't work in Firefox

### ISSUE THREAD

**Issue by fejesbence** [kaorun343/vue-property-decorator#2]
I successfully compiled my project with TypeScript, but this line caused me some trouble:

```
(componentOptions.watch || (componentOptions.watch = {}) as any)[path] = {handler, deep, immediate}
```
In Firefox, every object has an implicit watch function (see [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/watch)), which is a non-false value, so the default expression will never evaluate.

I fixed it with this workaround:
```
if (typeof componentOptions.watch !== 'object') {
  componentOptions.watch = {}
}
(componentOptions.watch as any)[path] = { handler, deep, immediate }
```
I am no expert in TypeScript/ES6, so there might be a better solution.

**Comment by kaorun343** [comment]
Thanks for reporting this issue. I didn't know that...
I'll fix it soon.

**Comment by kaorun343** [comment]
done.
