### ISSUE TITLE
Use with Babel

### ISSUE THREAD

**Issue by walleXD** [kaorun343/vue-property-decorator#20]
Does this library work with Babel?

It seems that @Component works but others like @Prop do not work and Vue complains: 
```
TypeError: Cannot redefine property
```
Let me know & thanks in advance!

**Comment by walleXD** [comment]
Just realized that this library only works with typescript given differences between the way typescript and babel handle decorators based on this [issue](https://github.com/vuejs/vue-class-component/issues/50).

**Comment by kolis** [comment]
This should really be mentioned clearly in the main readme!
