### ISSUE TITLE
How to use Enums with Props?

### ISSUE THREAD

**Issue by khrome83** [kaorun343/vue-property-decorator#202]
Is there any way to get type checking with Enums. I know that if I pass a invalid value, it will ignore it and apply the default which is nice. But I don't get any type checking.

```vue
<template>
  <section :class="theme">
    <div class="container" :class="layout">
      <slot/>
    </div>
  </section>
</template>

<script lang="ts">
import { Component, Prop, Vue } from "nuxt-property-decorator";

export enum Layouts {
  Small = "small",
  Medium = "medium",
  Large = "large"
}

export enum Themes {
  Light = "light",
  Grey = "grey",
  Dark = "dark"
}

@Component({})
export default class BaseSection extends Vue {
  @Prop({ default: Layouts.Medium })
  private layout!: Layouts;
  @Prop({ default: Themes.Light }) private theme!: Themes;
}
</script>

<style scoped>
section {
  font-family: "Montserrat", sans-serif;
}

.container {
  padding: 0.5rem 2.5vw 1.5rem;
  max-width: 90rem;
  margin: 0 auto;
}

.small {
  padding: 2rem 0;
}

.medium {
  padding: 4rem 0;
}

.large {
  padding: 6rem 0;
}

.light {
  background-color: #fff;
}

.grey {
  background-color: #e1e4ea;
}

.dark {
  background-color: #010b19;
  color: #fff;
}
</style>

```

**Comment by kaorun343** [comment]
@khrome83 

Hi.

How about doing like this below.

```ts
@Component({})
export default class BaseSection extends Vue {
  @Prop({ default: Layouts.Medium, validator: layout => Layouts[layout] !== undefined })
  private layout!: Layouts
}
```

**Comment by khrome83** [comment]
@kaorun343 - yeah that works with custom prop type validation error. 

Out of curosity, is it possible to make this a function of type, where you can specify the enum, and it wraps it in a custom validator?

Otherwise this is a lot of boilerplate code.

**Comment by kaorun343** [comment]
This library only supports the features that is available at Vue itself.

Instead, you can define `EnumProp` function like this below to avoid writing a lot of boilerplate code.

```ts
enum Fruit {
    Apple = 'Apple',
    Banana = 'Banana',
}
function EnumProp<T extends string | number>(d: T, e: Record<T, any>) {
    return {
        default: d,
        validator(v: T) {
            return e[v] !== undefined
        }
    }
}

@Component
class YourComponent extends Vue {
  @Prop(EnumProp(Fruit.Apple, Fruit)) fruit!: Fruit
}
```

**Comment by khrome83** [comment]
@kaorun343 - quick question about the code you wrote - 

If the Enum response is lowercase this fails. I guess `v` is the Type instead of the value of `Fruit['Apple']`.

```
Argument of type 'typeof Fruit' is not assignable to parameter of type 'Record<Fruit.Apple, any>'.
  Property 'apple' is missing in type 'typeof Fruit' but required in type 'Record<Fruit.Apple, any>'.Vetur(2345)
```

```ts
enum Fruit {
    Apple = 'apple',
    Banana = 'banana',
}
function EnumProp<T extends string | number>(d: T, e: Record<T, any>) {
    return {
        default: d,
        validator(v: T) {
            return e[v] !== undefined
        }
    }
}

@Component
class YourComponent extends Vue {
  @Prop(EnumProp(Fruit.Apple, Fruit)) fruit!: Fruit
}
```

**Comment by kaorun343** [comment]
Then, how about this? I made its type checking loose but it's not problem, I think.

```ts
function EnumProp(d: string | number, e: Record<any, any> { // <- Record is changed 
  return {
    default: d,
    validator: v => e[v] !== undefined,
  }
}
```

**Comment by winklerrr** [comment]
So currently there is no solution to set the `type` of the `@Prop` annotation correctly?

I tried:

```
enum MyEnum {
  One = "one1",
  Two = "two2"
}

@Prop({type: Object as PropType<MyEnum>}) myEnum!: MyEnum;

<my-component :myEnum="MyEnum.One" />
```

The error looks like this:

> Invalid prop: type check failed for prop "myEnum". Expected Object, got String with value "one1".

**Comment by kaorun343** [comment]
@winklerrr In your case, `type` should be `String` instead of `Object`

```ts
@Prop({ type: String })
```

**Comment by drewcook** [comment]
If you are writing it in the SFC style with Vue 3, you can cast your prop type to that of the enum type.  This is how the syntax would look within the `<script>` tag:

```jsx
<script lang="ts">
  export enum Layouts {
    Small = 'small',
    Medium = 'medium',
    Large = 'large'
  }
  
  export enum Themes {
    Light = "light",
    Grey = "grey",
    Dark = "dark"
  }
  
  export default {
    name: 'Layout',
    props: {
      layout: {
        type: String as () => Layouts // cast it
        default: Layouts.Medium
      },
      theme: {
        type: String as () => Theme // cast it
        default: Theme.Light
      },
    },
  }
</script>
```

This way, you can work with your enums within TypeScript and allow the API of the component to support native strings as props when implementing it throughout the application.

**Comment by winklerrr** [comment]
@drewcook @kaorun343 why does it need to be a cast from type `string` instead of type `object`?

**Comment by kaorun343** [comment]
Because the enum objects that you defined have type of String values.
What the type of `"one1"` ? It's type of String. How about `"two2"`? It's also type of String.
The runtime error you wrote told you the reason clearly why you had to pass `String` instead of `Object`.
