### ISSUE TITLE
Optional Props in examples are typed incorrectly, if they don't have default values they should be typed as a union with undefined

### ISSUE THREAD

**Issue by stephantabor** [kaorun343/vue-property-decorator#206]
Given this component, slightly modified from examples:
```ts
import { Vue, Component, Prop } from 'vue-property-decorator';

@Component
export default class YourComponent extends Vue {
  @Prop(String) readonly label!: string;

  get uppercaseLabel() {
    return this.label.toUpperCase();
  }
}
```

and this use of it:
```html
<your-component>Hello World</your-component>
```

when you don't pass the optional `label` prop, you will get a runtime error from calling `toUpperCase` on `undefined`

The proper typing of the `label` in this case is `string | undefined`, which would cause the typescript compiler to warn you about the `toUpperCase` issue.

The only time that props don't need a union type with `undefined` is when you explicitly set a `default` value or mark them as `required`.

**Comment by kaorun343** [comment]
Hi.

Thanks for your suggestion! It should be written correctly. I'll update the README.
