### ISSUE TITLE
[Feature Request] -- @RequiredProp(Constructor)

### ISSUE THREAD

**Issue by stephantabor** [kaorun343/vue-property-decorator#207]
I find myself typing out a lot of prop definitions similar to:

```ts
@Prop({ type: String, required: true }) label!: string;
```

it would be neat to be able to just do 

```ts
@RequiredProp(String) label!: string;
```

**Comment by kaorun343** [comment]
Hi.

Thanks for your suggestion.

You can create this decorator by yourself.

```ts
export function RequiredProp(type: any) {
  return Prop({ type, required: true })
}
```

Currently, I won’t add this decorator into this library, I think.
