### ISSUE TITLE
require("reflect-metadata");

### ISSUE THREAD

**Issue by CmdrShepardsPie** [kaorun343/vue-property-decorator#21]
I'm implementing Inversify for IoC and DI in my Vue project, and discovered that Vue Property Decorator has `require("reflect-metadata");` in its entry point, so I can't import it in my polyfills, but I need to load it before I can use Inversify, and I need to use Inversify before Vue Property Decorator has loaded. How can I get around this, or can you do something on your end to remove it and advise people to add it to their polyfills themselves?

Thanks

**Comment by kaorun343** [comment]
@CmdrShepardsPie

Hi
If you try to import `reflect-metada` in your polyfills, what happened to your project?

Also, this library uses it to reduce library users' typing times.

**Comment by kaorun343** [comment]
I'll close this issue because of inactivity.
