### ISSUE TITLE
[Question] How to define a numbers Array

### ISSUE THREAD

**Issue by duranivan** [kaorun343/vue-property-decorator#212]
At the moment I was able to define an array for a prop, say

```
  @Prop(Array) private data!: number[];
```

and although this check on runtime whether an array is passed or not (e.g. if a string is passed, it will give me an error in the browser console), still I am able to pass an array of any type, and it won't give an error (say `[1, 'hello', 2]` will be OK).

Is it possible to check for such types for props? For example, something like `  @Prop(Array<number>) private data!: number[];`?

Thanks in advance!

**Comment by kaorun343** [comment]
@duranivan 
Hi.
If you'd like to check the items of the array defined as a prop value, it's needed to use `validator` options, and they're going to be checked them at runtime.

```ts
@Component
class MyComponent extends Vue {
  @Prop({
    type: Array, 
    validator: data => data.every(item => typeof item === 'number'),
  }) 
  private data!: number[]
}
```

**Comment by duranivan** [comment]
Great, thanks!
