### ISSUE TITLE
How to use @PropSync with Prop import?

### ISSUE THREAD

**Issue by BetaF1sh** [kaorun343/vue-property-decorator#216]
## Error detail
```ts
18:3 Cannot find name 'PropSync'.
    16 | @Component
    17 | export default class Place extends Vue {
  > 18 |        @PropSync('place', {type: Array} ) data!: place[]
```

How to use [`@PropSync`](https://github.com/kaorun343/vue-property-decorator#-propsyncpropname-string-options-propoptions--constructor--constructor---decorator) decorator with Prop decorator import?

I can't find PropSync decorator from your module.

**Comment by kaorun343** [comment]
@BetaF1sh 
Hi.
Please check the latest version '8.2.0'.

**Comment by bestickley** [comment]
I'm still getting this error with 8.2.1

**Comment by bestickley** [comment]
Never mind. I had to restart VS Code for Vetur to pick up on npm updates. However, the docs could be  updated to show the correct imports :)
