### ISSUE TITLE
[v8.2] TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by razorness** [kaorun343/vue-property-decorator#219]
Version `8.1.1` is working fine. Just upgraded to `8.2.0` and got:
`TypeError: Class extends value undefined is not a constructor or null`

Here is the code of `index.vue`:

```vue
<script lang="ts">
	import {Component, Vue} from "vue-property-decorator";

	@Component
	export default class Index extends Vue {
	}  
</script>
```

Here is my `tsconfig.json`:
```json
{
	"compilerOptions": {
		"target": "esnext",
		"module": "esnext",
		"moduleResolution": "node",
		"lib": [
			"esnext",
			"esnext.asynciterable",
			"dom"
		],
		"esModuleInterop": true,
		"experimentalDecorators": true,
		"allowJs": true,
		"sourceMap": true,
		"strict": true,
		"noImplicitAny": false,
		"noEmit": true,
		"baseUrl": ".",
		"paths": {
			"~/*": [
				"./*"
			],
			"@/*": [
				"./*"
			]
		},
		"typeRoots": [
			"node_modules/@types",
			"@types"
		],
		"types": [
			"@types/node",
			"@nuxt/vue-app"
		]
	}
}
```
Typescript version: `3.5.2`

It's a project built on  Nuxt.js (`v2.8.1`) and Webpack (`v4.34.0`) which runs great with `v8.1.1`.

**Comment by tcastelly** [comment]
I have the same problem, I have to import Vue like this:

```javascript
import { Component } from 'vue-property-decorator';
import Vue from 'vue''
```

**Comment by kaorun343** [comment]
@razorness 
@tcastelly 

Hi.
Thanks for this reporting. I changed TypeScript config so this issue happened. I've already fixed this, so please check the latest version `8.2.1` .

**Comment by tcastelly** [comment]
It works for me thank you!

**Comment by flyingace** [comment]
I am running into a similar problem using Vue Property Decorator v8.3.0 and Vue v2.6.10. The component I'm testing imports a mixin, and that is where the error is being thrown:
```
TypeError: Class extends value undefined is not a constructor or null

      24 |     },
      25 | })
    > 26 | export default class ControlMixin extends Vue {
```
Vue is being imported into the mixin component as follows:
```
import Vue from "vue";
import Component from "vue-class-component";
import { Prop } from "vue-property-decorator";
```
I've tried moving the import of Vue to come after `Component` and `{ Prop }` but that has effected no change in the error message. The only thing that does seem to prevent the error is to have `Vue` imported from `vue-property-decorator` as `import { Prop, Vue } from "vue-property-decorator";` Is that the only solution here?
