### ISSUE TITLE
is #102 going to be fixed?

### ISSUE THREAD

**Issue by nitwhiz** [kaorun343/vue-property-decorator#221]
#102 is a weird issue, is this workaround supposed to be the solution?

Why does `@Component` not retrieve the name by it's class name?

**Comment by kaorun343** [comment]
@nitwhiz 
Hi.
The issue is caused by UglifyJS. Usually, UglifyJS is used against production build. 
The classname is modified by UglifyJS. Therefore, explicit naming is needed.
There's nothing to do to fix that issue.

**Comment by nitwhiz** [comment]
But I'm using terser. Is terser based on uglify?

**Comment by kaorun343** [comment]
In order to make code size shorter, UglifyJS modify each class name. I don't know well about terser, but probably it'll do the same work: rename classes.

**Comment by nitwhiz** [comment]
thanks for the info, i guess recursive components aren't used that often that it is going to be a problem.
