### ISSUE TITLE
Extending a  mixin and a class

### ISSUE THREAD

**Issue by seifsay3d** [kaorun343/vue-property-decorator#225]
I am not sure how is it possible to extend a `class` and a `mixin` at the same time.

I have tried the following:

```
@Component({
  name: 'duck'
  mixins: [someMixin],
})
export default class Duck extends Animal {
// using mixin methods here causes typescript error.
}
```

The only current workout I have is to add thix mixin to the component Animal, which is not really optimal.

```
export default class Animal extends mixins(mixinA, someMixin) {
}
```

I guess it would be nice to add to the docs if there is a way, I'm willing to do a PR once I know the solution :)

**Comment by sheijne** [comment]
A bit late to the party (maybe this issue should be closed?), but in case you never solved this to your needs:

Seems like a design problem not really a bug. What is the functionality of your mixin? Your example uses terms like `Duck` and `Animal` and your `someMixin` variable name doesn't seem to relate to it, and therefore is hard to interpret.

Have you tried:
```
class Duck extends Mixins(Animal, someMixin) {}
```

This seems to be the way this is designed and should work . Unless I misunderstood your problem the above solution should be sufficient.

You could also go for something like:
```
class Bird extends Mixins(Animal, eggMixin, featherMixin, beakMixin) {}
class Duck extends Bird {}
```

This would also allow you to bridge the behavior of your parent class and the required mixins for any future child classes.

**Comment by seifsay3d** [comment]
Yup you are right, it's a design problem and not a bug. Thank you
