### ISSUE TITLE
Can i use mixins global in vue? i am use typescript with vue

### ISSUE THREAD

**Issue by CuongStf** [kaorun343/vue-property-decorator#226]
```
mounted() {
    Vue.$notify("OK", "success", "notify", 2000);
  }
```
if i call function $notify (in file mixins and declared in main.ts) by this or Vue. ts will show error this function doesn't exist in module. So how to can call this function in the component?

**Comment by bestickley** [comment]
I have this same question. I've tried augmenting types shown here: https://vuejs.org/v2/guide/typescript.html#Augmenting-Types-for-Use-with-Plugins
But still no luck.

**Comment by bestickley** [comment]
Solution:
`
// src/types.d.ts
import Vue from "vue";

declare module "vue/types/vue" {
  interface Vue {
    toCurrency(number: number): string;
  }
}
`
`
// src/App.vue
const amount = this.toCurrency(1000);
`

**Comment by CuongStf** [comment]
Can you sure it work? I also do that but it's not working

**Comment by bestickley** [comment]
Yep, I'm sure it works for me. I'm not sure why it wouldn't be working for you :(

**Comment by kaorun343** [comment]
@CuongStf 
Hi.
Could you ask this question at Vue's official forum?
This issue is not caused by this library.
Thanks.
