### ISSUE TITLE
@InjectReactive computed property does not update

### ISSUE THREAD

**Issue by edave64** [kaorun343/vue-property-decorator#227]
I have two components: A `Provider` and a `Receiver`. The `Provider` defines a `@ProvideReactive('msg') public provider_msg` and the `Receiver` defines `@InjectReactive('msg') public injected_msg`.

`injected_msg` is not updated when `provider_msg` changes. The `__reactiveInject__.msg` does get updated, but doesn't seem to cause the `injected_msg` to update.

#### Provider.vue
```vue
<template>
  <div>
    <slot />
    <button @click="onClick">Change to B</button>
  </div>
</template>
<script lang="ts">
import Vue from 'vue'
import { ProvideReactive, Component } from 'vue-property-decorator';
@Component({})
export default class Provider extends Vue {
  @ProvideReactive('msg') public provider_msg!: string | undefined;
  created() { this.provider_msg = 'A'; }
  public onClick() { this.provider_msg = 'B'; }
}
</script>
```
#### Receiver.vue
```vue
<template>
  <h1>{{ injected_msg }}</h1>
</template>
<script lang="ts">
import { Component, Vue, InjectReactive } from 'vue-property-decorator';

@Component({})
export default class Receiver extends Vue {
  @InjectReactive('msg') public injected_msg!: string | undefined;
}
</script>
```
#### App.vue
```vue
<template>
  <div id="app">
    <Provider>
      <Receiver />
    </Provider>
  </div>
</template>
<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
import Receiver from './Receiver.vue';
import Provider from './Provider.vue';

@Component({ components: { Receiver, Provider } })
export default class App extends Vue {}
</script>
```

### Expected behavior
The receiver should show 'A' initially, and show 'B' once the button in the `Provider` is clicked.

### Actual behavior
The receiver shows 'A', and doesn't change when the button in the `Provider` is clicked. According to the vue debugging tools in chrome, `__reactiveInject__.msg` of the Receiver is updated, but `injected_msg` is not.

**Comment by enekesabel** [comment]
@edave64 I think it's the same caveat explained here: [https://github.com/vuejs/vue-class-component#undefined-will-not-be-reactive](https://github.com/vuejs/vue-class-component#undefined-will-not-be-reactive).
The workaround is initializing your provided value:
`@ProvideReactive('msg') public provider_msg!: string ='A';`

**Comment by edave64** [comment]
Thank you, @enekesabel! When using null or initializing as `'A'` works. :)

**Comment by scscgit** [comment]
A note if someone searches for this issue, even though the providing side should be initialized, it seems the injected side shouldn't, as that would cause a warning of `[Vue warn]: The computed property "myProperty" is already defined in data.`. I'd suggest to explicitly mention both of these requirements in Readme docs, as it's just too painful to debug.
