### ISSUE TITLE
how dose it import PropOptions & WatchOptions from vue?

### ISSUE THREAD

**Issue by gaokun** [kaorun343/vue-property-decorator#229]
I didn't see `PropOptions & WatchOptions` were exported from vue;

And I try import like what it did in picture.  But doesn't work.

**Why `vue-property-decorator` can do this?**

Thanks

![image](https://user-images.githubusercontent.com/7044628/61765729-de12e200-ae10-11e9-8518-b15be147cae2.png)

**Comment by edave64** [comment]
The exports are [here](https://github.com/vuejs/vue/blob/b7c2d9366cf731a1551286b8ac712e6e0905070e/types/index.d.ts#L18-L21). The definitions are [here](https://github.com/vuejs/vue/blob/b7c2d9366cf731a1551286b8ac712e6e0905070e/types/options.d.ts#L153-L158) and [here](https://github.com/vuejs/vue/blob/b7c2d9366cf731a1551286b8ac712e6e0905070e/types/options.d.ts#L174-L177).

It should work in any project.

**Comment by gaokun** [comment]
Oh, god, I tested it in a `js`, not `ts` project. Forgive me.

Many thanks @edave64

**Comment by StarkShang** [comment]
Is PropOptions exsits in vue 3.0?
