### ISSUE TITLE
How to use @Model along with a @Prop property

### ISSUE THREAD

**Issue by alexjoverm** [kaorun343/vue-property-decorator#23]
`@Model('change') checked` translates to:

```javascript
{
  model: {
    prop: 'checked',
    event: 'change'
  }
}
```

But then you cannot use @Prop() checked to define the property, since it is used already. What's the workaround for it?

```typescript
import Vue from 'vue'
import { Component, Prop, Model } from 'vue-property-decorator'

@Component({})
export default class Hello extends Vue {
  @Prop() checked: string
  @Model('changed') checked: boolean
}
```

**Comment by kaorun343** [comment]
@alexjoverm 

Hi.
Will it work?

```ts
class Hello {
  @Model('changed')
  @Prop() checked: string
}
```

**Comment by alexjoverm** [comment]
Don't know how I didn't come up with that xD.

Working as a charm! Thanks

**Comment by alexjoverm** [comment]
@kaorun343 Btw, probably is not a bad idea to update the Readme with that example for the `@Model`

**Comment by kaorun343** [comment]
PR is welcome 😄
