### ISSUE TITLE
@Prop pass an array

### ISSUE THREAD

**Issue by shenmingyon** [kaorun343/vue-property-decorator#231]
### Environment is the vue + typescript;
A bug is found when the prop parameter is an array,
example:
 (In the child component)
```ts
  @Prop({
    type: Array,
    required: true,
    default: () => {
      return [];
    }
  })
  saledata: Array<any> = [];
```
ERROR:vue.runtime.esm.js:619 [Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "saledata";
(tip:This violates the rules for subcomponents that modify prop)；
Then:
```ts
  @Prop({
    type: Array,
    required: true,
    default: () => {
      return [];
    }
  })
  saledata:Array<any>;
```
ERROR:Property 'saledata' has no initializer and is not definitely assigned in the constructor.
(tip:There is a violation of typescript variable declaration rules)；
Then:
I find this BUG in all types;

Here's my solution:
```ts
  @Prop({
    type: Array,
    required: true,
    default: () => {
      return [];
    }
  })
  saledata?: Array<any>;
```
Make parameters optional to avoid typescript's strict mode type checking；
or Or declare of type any

**Comment by kaorun343** [comment]
@shenmingyon 
Hi.
In your case, you need to add `!` like this below.

```ts
class YourComponent extends Vue {
  @Prop({ type: Array, required: true, default: () => { return [] } })
  saledata!: Array<any>
}
```
