### ISSUE TITLE
TS6133: 'created' is declared but its value is never read.

### ISSUE THREAD

**Issue by wangyajundev** [kaorun343/vue-property-decorator#233]
export default class Login extends Vue {
    private created(): void {
        //to do...	
    }
}

**Comment by kaorun343** [comment]
@wangyajundev 
Hi.
Please check this page. Thanks.
https://stackoverflow.com/questions/44565671/ignore-ts6133-import-is-declared-but-never-used

**Comment by wangyajundev** [comment]
Find a good solution：

tsconfig.json:
compilerOptions: {
  noUnusedLocals: false
}
