### ISSUE TITLE
Prop with type 'any' got [Vue Warn] ... Expected Object,...

### ISSUE THREAD

**Issue by Fonigle** [kaorun343/vue-property-decorator#234]
when I try to define `any` type prop like this (with reflect-metadata):
```typescript
@Prop()
readonly value?: any;
```
and using like this:
```HTML
<mdc-list-item :value="1"></mdc-list-item>
```
then got some [Vue warn] like this:
![image](https://user-images.githubusercontent.com/25600355/62340500-5f096200-b512-11e9-87fa-cfe36fb9971d.png)

it seems like the reflected type is `Object` when set the type of prop to `any`,
![image](https://user-images.githubusercontent.com/25600355/62340793-5d8c6980-b513-11e9-9739-53afe175fa6e.png)

so is there any solutions?

-----
I have checked #69, but I'm using the lasted version `8.2.1` and it still doesn't work.

**Comment by fluidsonic** [comment]
My workaround to disable type checking is this:

```ts
@Prop({ default: '', type: null as any }) value!: any
```

`null` prevents this library for inferring the type for this property.
