### ISSUE TITLE
Interface as @Prop type

### ISSUE THREAD

**Issue by senner007** [kaorun343/vue-property-decorator#248]
How come I can't have the type set to an interface like this:
```
    export default interface ITodo {
        name : string;
        done : boolean;
    }

    @Component
    export default class Todo extends Vue {
        @Prop({required : true, type : ITodo}) private todo!: ITodo;
    }
```

**Comment by asbermudez** [comment]
@senner007 It's related to the fact that the `type` property maps to this:
https://vuejs.org/v2/guide/components-props.html#Type-Checks

You cannot use typescript types in runtime because they don't exist, Typescript only exist before transpiling :)

**Comment by asbermudez** [comment]
Seems it might be a workaround with this:
https://github.com/kaorun343/vue-property-decorator#if-youd-like-to-set-type-property-of-each-prop-value-from-its-type-definition-you-can-use-reflect-metadata

**Comment by hectorj** [comment]
This might be helpful https://frontendsociety.com/using-a-typescript-interfaces-and-types-as-a-prop-type-in-vuejs-508ab3f83480

**Comment by kaorun343** [comment]
`Interface`  cannot be used as `type`, instead, set `Object`, please.
