### ISSUE TITLE
PropSync throw exception 

### ISSUE THREAD

**Issue by sonicwang1989** [kaorun343/vue-property-decorator#258]
If i defined the variable like this 
```
@PropSync('visible', { type: Boolean })
  dialogVisible: boolean = false;
```
It will throw a exception like this
```
[Vue warn]: The computed property "dialogVisible" is already defined in data.
```

If i remove the "false" value, it will be ok!

**Comment by FloryanFilip** [comment]
Why would you declare a Prop value? You only need to write 
`@PropSync('visible', { type: Boolean }) dialogVisible!: boolean;` and bind it to anything in your template
