### ISSUE TITLE
Basic linting support

### ISSUE THREAD

**Issue by akoidan** [kaorun343/vue-property-decorator#267]
Provide tslinter rules with
```
"extends": ["./node_modules/vue-property-decorator/tslint.json"],
"rulesDirectory": ["node_modules/vue-property-decorator/tslint-rules"],
```
So they would warn if vue components use native api instead of vue-property-decorator api.
This would enforce new users to write withing the same style. Some of these rules can be easily done with finding keywords like `this.$refs.button` or something like that

**Comment by kaorun343** [comment]
I wouldn't like to enforce any rules by this library. These are defined by teams, projects, and so on.
Thanks for your suggestion.
