### ISSUE TITLE
Need in default way to get types

### ISSUE THREAD

**Issue by viT-1** [kaorun343/vue-property-decorator#279]
I see vue-property-decorator.d.ts in lib directory, but it is not the standart way to pick up typings.
Please, provide @types/vue-property-decorator or rename vue-property-decorator.d.ts to index.d.ts

**Comment by kaorun343** [comment]
@viT-1 
Hi.
Did you meet some problems that caused by the current way of providing the definition file?

**Comment by viT-1** [comment]
I don't remember my case (may be I found workaround), but may be [this link](https://github.com/microsoft/TypeScript/issues/27956#issuecomment-536538846) helps you.

**Comment by kaorun343** [comment]
I've renamed the file.
