### ISSUE TITLE
Breaking my jest tests...

### ISSUE THREAD

**Issue by blocka** [kaorun343/vue-property-decorator#28]
I'm using ts-jest, if it's relevant. When I use the Vue export from vue-property-decorator, I get:
```
TypeError: Object prototype may only be an Object or null: undefined
        at setPrototypeOf (native)
```

This doesn't happen when I use the export from vue itself.

**Comment by kaorun343** [comment]
Which version of Vue and vue-property-decorator are you using?

**Comment by blocka** [comment]
vue 2.3.0
vue-property-decorator 5.1.0

**Comment by kaorun343** [comment]
Could you provide a reproduction?
Unfortunately, I haven't used jest framework...

**Comment by blocka** [comment]
I put a reproduction in repo. Here is the test which demonstrates that the
Vue export is undefined
https://github.com/blocka/issue-with-vue-property-decorator-vue-export/blob/master/src/test.test.ts

you can run with npm install && npm test

**Comment by kaorun343** [comment]
I found the reason of this issue.
In your project, `vue.common.js` is used. `module.exports = Vue` is written in this file.
However, `vue-property-decorator` is trying to import `exports.default = Vue` or `export default Vue`, so the error happens.

**Comment by blocka** [comment]
What should i do instead?

**Comment by kaorun343** [comment]
If you can import `vue.esm.js` instead `vue.common.js`, it'll work well. 
However, I'm not good at jest, so if it doesn't work well, I not importing `Vue` from 'vue-property-decorator` will be the solution of this issue...

**Comment by rndmerle** [comment]
Hello.

Trying to overcome the same issue.

```
module.exports = {
    testMatch: ['**/?*.spec.ts'],
    "moduleNameMapper": {
        "^vue$": "vue/dist/vue.esm.js"
    },
    "moduleFileExtensions": [
        "ts",
        "js",
        "json",
        "vue"
    ],
    "transform": {
        "\.ts$": "<rootDir>/node_modules/ts-jest/preprocessor.js",
        "\.js": "<rootDir>/node_modules/babel-jest",
        "\.vue$": "<rootDir>/node_modules/jest-vue"
    },
    "snapshotSerializers": [
        "<rootDir>/node_modules/jest-serializer-vue"
    ],
);
```
Is this good in theory?

Test logs:
```
C:\Users\rmerle\Dev\portal\front-end\node_modules\vue\dist\vue.esm.js:10190
    export default Vue$3;
    ^^^^^^

    SyntaxError: Unexpected token export

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:306:17)
      at Object.<anonymous> (jest.setup.ts:1:156)
```

Not sure what you meant by "not importing Vue from 'vue-property-decorator` will be the solution of this issue". Is it someting on user-side or your side?

**Comment by kaorun343** [comment]
@rndmerle 

Hi.

My suggestion is a user-side solution.

**Comment by rndmerle** [comment]
Ok now I got it.
The issue is from the vue import I'm doing in my test file.
So no business with your lib 
Thanks and sorry for your time.

**Comment by rndmerle** [comment]
Nm actually it was working because I had removed the vue import from my component too, for testing purpose. But when the vue import gets back it's not working.
How is it possible to have a component not importing Vue ? (or I misunderstood maybe)

```
<template>
    <div></div>
</template>

<script lang="ts">
    import Vue from "vue";
    import {Component, Inject, Prop, Provide} from "vue-property-decorator";

    @Component
    export default class Badge extends Vue {
        // ...
    }
</script>
```

I tried to configure the `transformIgnorePatterns` Jest parameter so it transpiles `vue.esm.js` but I can't get it to work. Using `vue.common.js` would be easier I guess.

**Comment by rndmerle** [comment]
Eventually it works. I made ts-jest to preprocess the vue modules.
For anyone interested:
```
module.exports = {
    testMatch: ['**/?*.spec.ts'],
    "moduleNameMapper": {
        "^vue$": "vue/dist/vue.esm.js"
    },
    "moduleFileExtensions": [
        "js",
        "ts",
        "vue"
    ],
    "transform": {
        "\.(t|j)s$": "<rootDir>/node_modules/ts-jest/preprocessor.js",
        "\.vue$": "<rootDir>/node_modules/jest-vue"
    },
    "transformIgnorePatterns" : [
        "node_modules/(?!vue)"
    ],
    "snapshotSerializers": [
        "<rootDir>/node_modules/jest-serializer-vue"
    ],
};
```
And, quite importantly, in tsconfig.json:
```
// ...
"allowJs": true,
// ...
```

**Comment by jackple** [comment]
@rndmerle Is there a demo?
