### ISSUE TITLE
@Prop declaration with no options type

### ISSUE THREAD

**Issue by Danielg212** [kaorun343/vue-property-decorator#282]
I always used to declare props without specify the option type decorator, and It works fine even without `import 'reflect-metadata'`.
So I have 3 questions:

1.What is the difference between:

```
@Prop() items !: string[]
@Prop() exportType!: string
@Prop() showMenu!: boolean
```

vs

```
@Prop(Array) items !: string[]
@Prop(String) exportType!: string
@Prop(Boolean) showMenu!: boolean
```

2.When should I declare the Prop's type definition?
3.Why is it work to me without the `import 'reflect-metadata'` import?

Thanks!

**Comment by TaPO4eg3D** [comment]
`@Prop() items !: string[]`
Transpiles into:
 `
{
    props: {
        items: {}
    }
}
`

`@Prop(Array) items !: string[]`
Transpiles into:
 `
{
    props: {
        items: {
            type: Array
        }
    }
}
`

The second option gives you type-checking in the **runtime**, while typescript gives type-checking only in the **compile-time**.
