### ISSUE TITLE
Component inheritance

### ISSUE THREAD

**Issue by supproduction** [kaorun343/vue-property-decorator#286]
Hello do you supprort extending component like default vue `implementation?
```
import SurveyInputBase from './SurveyInputBase.vue';
  export default {
    extends: SurveyInputBase,
    props: [ 'placeholder' ],
  }
```

If it use via mixins, this way does not work

![image](https://user-images.githubusercontent.com/16482929/69810351-5d1b8b00-11f4-11ea-994a-f88cc2c64634.png)

![image](https://user-images.githubusercontent.com/16482929/69810188-057d1f80-11f4-11ea-8ac8-67134db067d0.png)

**Comment by juanfernandoe** [comment]
Hi,
I'm experiencing exactly the same issue working with NuxtJS.

@supproduction  how did you get over this?

**Comment by lazehang** [comment]
Although this is closed, why don't you use Mixins from vue-property-decorator instead of vue-class-component.
