### ISSUE TITLE
Compile error with Typescript 2.4

### ISSUE THREAD

**Issue by maccesch** [kaorun343/vue-property-decorator#29]
When doing this:

```typescript
@Prop(String)
name: string;
```

Typescript 2.4 reports a type error. It's probably necessary to extend the `Prop` parameter type from `PropOptions | Constructor[]` to

```typescript
PropOptions | Constructor[] | Contructor
```

**Comment by kaorun343** [comment]
Hi.

OK, I'll fix this.

**Comment by maccesch** [comment]
Awesome, thanks!

**Comment by kaorun343** [comment]
done.

**Comment by maccesch** [comment]
That was fast! Can I already install it via npm?

**Comment by kaorun343** [comment]
Yes.
