### ISSUE TITLE
How do I set inheritAttrs to false?

### ISSUE THREAD

**Issue by kpturner** [kaorun343/vue-property-decorator#295]
Using vue-property-decorator how would I set inheritAttrs to false as documented in this transparent wrapper example https://zendev.com/2018/05/31/transparent-wrapper-components-in-vue.html

**Comment by kaorun343** [comment]
@kpturner 

How about this?

```ts
import { Vue, Component } from 'vue-property-decorator'

@Component({ inheritAttrs: true })
class YourComponent extends Vue {}
```

**Comment by kpturner** [comment]
Thanks
