### ISSUE TITLE
[Request] Router decorator

### ISSUE THREAD

**Issue by chiqui3d** [kaorun343/vue-property-decorator#296]
```ts
@Route({
  path: '/',
  name: 'home',
  methods:['GET','POST']
})
@Component()
export default class HomeComponent extends Vue
```

**Comment by joeherold** [comment]
@chiqui3d Check this out: [vue-auto-routing](https://github.com/ktsn/vue-auto-routing)

**Comment by kaorun343** [comment]
@chiqui3d 
`vue-property-decorator` only contains helper decorators for Vue's options.
Currently, this library doesn't add any features for the libraries other than Vue, thanks.
