### ISSUE TITLE
No overload matches this call. Overload 1 of 2, '(plugin: PluginObject<unknown>

### ISSUE THREAD

**Issue by akai007** [kaorun343/vue-property-decorator#300]
![image](https://user-images.githubusercontent.com/10443550/74796198-db269400-5302-11ea-95e7-3f9c0e1b4e45.png)

**Comment by akai007** [comment]
could you help me to fix this?

**Comment by Lneedy** [comment]
You did not define the install method for test.vue, please see the official vue documentation!

**Comment by kaorun343** [comment]
@akai007 

Please use `Vue.component` instead.

```ts
Vue.component('test', Test)
```

`Vue.use` is not for registering components.
