### ISSUE TITLE
Add support for @Watch to handle functions

### ISSUE THREAD

**Issue by Chris2011** [kaorun343/vue-property-decorator#301]
In the official documentation of vuejs using vm.$watch (https://vuejs.org/v2/api/#vm-watch) it is possible to use a string to watch at or to use a function which returns an expression. @Watch can only handle strings. So this example:

`@Watch(() => this.myStore?.SmthState?.request?.get('categorization')?.pending, { deep: true })`

is not possible and will raise an error in the editor: `Argument of type '() => any' is not assignable to parameter of type 'string'.Vetur(2345)`

So please support functions in the @Watch decorator.

**Comment by kaorun343** [comment]
@Chris2011 

`@Watch` decorator is not able to receive watch function because this library affects `watch` option of ComponentOptions.
To support watch function, I have to think where to insert `vm.$watch`.
Thanks.

**Comment by Chris2011** [comment]
Thx for the info. Would be great to have a solution for that :)
