### ISSUE TITLE
Emit decorator, merge new and old value

### ISSUE THREAD

**Issue by tcastelly** [kaorun343/vue-property-decorator#308]
Hi,

I noticed a problem since the last release.

I create a component, use Watch and Emit to forward value changes. The parent component instead of retrieve the new variable, retrieve a merge of new and old value.

v 8.3.0
https://jsfiddle.net/05twh7qr/

v 8.2.2
https://jsfiddle.net/h57rqgb3/

**Comment by tcastelly** [comment]
Maybe link to this commit?

https://github.com/kaorun343/vue-property-decorator/commit/b9f0ba86b1b0a58164a19aba07ae82836a6c57a9#diff-a542f5e3653e6b2d1bd03489368849b9

**Comment by lzxb** [comment]
I also encountered this problem, and the production failed

**Comment by lzxb** [comment]
`
this.$emit(emitName, args);
Should be
this.$emit(emitName, ...args);
`

**Comment by tcastelly** [comment]
The v8.4.2 fix the issue
