### ISSUE TITLE
AMD Support

### ISSUE THREAD

**Issue by Micene09** [kaorun343/vue-property-decorator#31]
Looking at the tsconfig.json here, seems that the only module load pattern supported is CommonJs.

I'm trying to develop a boilerplate using this library but, I cannot require it in a Web view using requirejs.

As you can see from the vue-class-compoment project (build folder), the definition is in UMD style factory (checking for define.amd etc...). 

Ps. Thank you for the great job here...seriously.

**Comment by kaorun343** [comment]
@Micene09 

Hi.

I've done updating. Please check version 5.2.0

**Comment by Micene09** [comment]
@kaorun343
It's working perfectly now, thank you for the great job!!

For every dev that is trying to use it with requirejs:
Just add a path-mapping for reflect-metadata module (Reflect.js from node_modules...) into the configuration to make it work.
