### ISSUE TITLE
Mixin not working for me

### ISSUE THREAD

**Issue by mpjraaij** [kaorun343/vue-property-decorator#312]
Hi,

I'm trying to add a mixin in my component, but it doesn't seem to get added.

In my code I'm doing this:

```ts
import { Vue, Component, Mixins } from 'vue-property-decorator'

const inViewport = require('vue-in-viewport-mixin')

@Component({
  components: {
    ...
  }
})
export default class BasicProfile extends Mixins(Vue, inViewport) {
  ...
}

```

However the `vue-in-viewport-mixin` does not get loaded.

What am I doing wrong?

Thank you so much.

**Comment by tcastelly** [comment]
Hi,

Is `inViewport` extends `Vue`?

**Comment by mpjraaij** [comment]
Hi,

Thank you for asking! No it doesn’t. It’s a JS package (https://github.com/BKWLD/vue-in-viewport-mixin/blob/master/index.js)

**Comment by tcastelly** [comment]
You have to:

https://class-component.vuejs.org/guide/extend-and-mixins.html

```
As same as super class, all mixins must be declared as class components
```

**Comment by mpjraaij** [comment]
I've read that, the package is not mine though
Do I have to fork the package and write it in typescript?

**Comment by kaorun343** [comment]
@mpjraaij 

```ts
@Component({ mixins: [inViewport] })
export class YourComponent extends Vue {}
```

Could you try this?

**Comment by mpjraaij** [comment]
@kaorun343 

Thank you, I tried that. Unfortunately it does not work.

`console.log(inViewport)` does print the module properly, meaning it is being loaded

**Comment by kaorun343** [comment]
```ts
import inViewport from 'vue-in-viewport-mixin' // use 'import'

@Component({ mixins: [inViewport] })
export class YourComponent extends Vue {}
```

How about this?

**Comment by markSampson18** [comment]
I haven't previously passed **Vue** into the Mixins parentheses as follows
`export default class BasicProfile extends Mixins(**Vue**, inViewport) {`

You should get somethings working by removing **Vue** from the mixin.
`export default class BasicProfile extends Mixins(inViewport) {`

Would be good to know if you figured this out! @mpjraaij :)

**Comment by kaorun343** [comment]
This issue seems to be fixed because of vue-class-component's update.
