### ISSUE TITLE
Emit的参数问题

### ISSUE THREAD

**Issue by OliverFitz** [kaorun343/vue-property-decorator#315]
问题：当Emit有多个参数的时候，外层接收的参数格式不对
描述：@Emit('choiceApplication')
           handleChoiceApplication(item: any, travel: any) {  }
           这种写法，再8.4.0中，外层接受的参数也是两个，但是再8.4.1中外层拿到的是一个数组，第二个参数为undefined

**Comment by aldarund** [comment]
Can confirm, its new issue was working fine before.
probably related\same as https://github.com/kaorun343/vue-property-decorator/issues/308

**Comment by kaorun343** [comment]
Please write your issue in English, instead.
Thanks.
