### ISSUE TITLE
[Help] Async Component 

### ISSUE THREAD

**Issue by paolog22** [kaorun343/vue-property-decorator#318]
I was trying to load a component in async manner to show a 'Loading' indicator and or add delay and timeout 

Please refer to screenshot
![image](https://user-images.githubusercontent.com/12680745/80438768-883b0f80-8937-11ea-935d-a1f73a4e30d2.png)
`PrescriptionForm` is not recognize and typescript is throwing an error 

What am i missing here ? 

thank you

Plugins
typescript@3.7.5
vue-class-component@7.2.3
vue-property-decorator@8.4.1
vue@2.6.11
vue-router@3.1.6

**Comment by paolog22** [comment]
up

**Comment by nicolidin** [comment]
Hey I think the better approach is to use this lib: https://github.com/posva/vue-promised

**Comment by paolog22** [comment]
@nicolidin thanks, but what i am asking is the already available from vue for a lesser boilerplate on my code. does vue-promise also lazy load the component ?

**Comment by kaorun343** [comment]
Could you ask this question at vue-class-component repository?
