### ISSUE TITLE
computed get property cache 

### ISSUE THREAD

**Issue by John0King** [kaorun343/vue-property-decorator#320]
when I use  follow code , that the get property will be cached,  and when I get this property next time,  there no log be print
```
obj:any = {};
get obj2(){
    console.log("get ")
    return {...obj, a: new Date()}
}

```

suggest to add `@Computed({ cache:false })`   decorator

**Comment by OzoneGrif** [comment]
If you don't want the variable to be cached, just use a method instead:
```
obj: any = {};
getObj2() {
  console.log("not cached");
  return {...obj, a: new Date()};
}
```
