### ISSUE TITLE
If an array is not initialized, it is not reactive

### ISSUE THREAD

**Issue by muyiwei** [kaorun343/vue-property-decorator#333]
example：

`export default class App extends Vue {

  list!: Array<any>;

  created() {

    this.list = [1, 2, 3, 4];

    setTimeout(() => {

      this.list.splice(1, 1);

    }, 1000);
  }
}`

`<div v-for="(item, index) in list" :key="index">{{ item }}</div>`

I hope it show 1,3,4 in page After a second
but is still show 1,2,3,4 in page.
If i  init the list ,it show  1,3,4 in page After a second;
`  list!: Array<any> = []`
Is this a bug?

**Comment by chanlito** [comment]
@muyiwei Note that if the initial value is undefined, the class property will not be reactive which means the changes for the properties will not be detected from https://class-component.vuejs.org/guide/class-component.html#data
