### ISSUE TITLE
Error: This dependency was not found

### ISSUE THREAD

**Issue by bumhyunkim** [kaorun343/vue-property-decorator#337]
when run build, failed to compile with 1 errors

*  vue-class-component in ./node_modules/vue-property-decorator/lib/vue-property-decorator.js

After  npm install --save vue-class-component in that directory, It builds

**Comment by lambdalisue** [comment]
Maybe because of https://github.com/kaorun343/vue-property-decorator/commit/c21a779e4bbeddf9b085ce635ba718bb2625936c

**Comment by kaorun343** [comment]
Hi.
I moved `vue-class-component` to `peerDependencies`, so users need to install it by themselves.
Thanks.
