### ISSUE TITLE
Property 'x' does not exist on type 'y'

### ISSUE THREAD

**Issue by jetpack3331** [kaorun343/vue-property-decorator#338]
**Describe the bug**
After upgrading the packages i'm getting error
Property 'x does not exist on type 'y'.

Based on this issue it seems that only one dependency vue-class-component breaks this but it's fixed in the 
v7.2.5

I suggest update the dependency to that version.

Linking Issue describing the problem too: https://github.com/kaorun343/vue-property-decorator/issues/335

### Reproduced by
- create  mixin defining it's own properties

- create class extending from that mixin and should access the property from that mixin.
```
class Abc extends Mixins(MixinA, MixinB)

method () {
   console.log(MixinA.property);
}
```

- Then error will occur
- - Property 'MixinA.property' does not exist on type 'Abc'

**Comment by kaorun343** [comment]
I'll close this issue because I updated dependencies.
