### ISSUE TITLE
Name for component?

### ISSUE THREAD

**Issue by CKGrafico** [kaorun343/vue-property-decorator#34]
Not sure if we are doing something wrong or is a bug on vue, let me explain:

When we create a component we usually add 'Component' to the name, for example:
`export class SwitchButtonBoxComponent extends SwitchButtonComponent {}`

When we add this component to his parent the only way that we've found to change his tag name is:
```
@Component({
    components: {
        'switch-button-box': SwitchButtonBoxComponent
    }
})
```

We have to do that because we don't want the 'Component' word on the tag name (I think is a normal thing)

But this is not the best scenario, we've tried that:
```
export class SwitchButtonBoxComponent extends SwitchButtonComponent {
     name: 'switch-button-box'
}
```

and on the other side

```
@Component({
    components: {
        SwitchButtonBoxComponent
    }
})
```

But is not working, is there any alternative or suggestion?

Thanks!

**Comment by kaorun343** [comment]
@CKGrafico 

Hi.

Here is an explanation of `name` option.
https://vuejs.org/v2/api/#name

Vue components don't use it for defining their tag name, whereas Angular components do so.

Therefore, I recommend you to do like this below.

```ts
import SwitchButtonBox from './YourSwitchButtonComponentBoxPath'

@Component({
  components: {
    SwitchButtonBox
  }
}
})
export class YourComponent {
}
```

**Comment by CKGrafico** [comment]
Your solution is to not use 'Component' on the name? you can't suggest that and close the issue xD

**Comment by kaorun343** [comment]
Yes. There's no way to do so. 😢 

I suggest you 2 ways.

1. `components: { 'switch-button-box': SwitchButtonBoxComponent }`
2. `components: { SwitchButtonComponent }`

Here is a bit more detailed example.

```ts
// SwitchButtonBoxComponent.ts
@Component
export default class SwitchButtonBoxComponent extends SwitchButtonComponent {
}
```

```ts
import SwitchButtonBox from './SwitchButtonBoxComponent.ts'

@Component({
  components: {
    SwitchButtonBox
  }
}
})
export class YourComponent {
}
```

**Comment by CKGrafico** [comment]
mm thanks.. if there is no way maybe better solution could be use alias...

```import {SwitchButtonBoxComponent as SwitchButtonBox} from './folder'```

**Comment by eladcandroid** [comment]
Why can't we use this approach? (taken from "vue-class-component")

import Vue from "vue";
import Component from "vue-class-component";
@Component({
  name: "AnotherName"
})
export default class YourName extends Vue {
}
