### ISSUE TITLE
default property value

### ISSUE THREAD

**Issue by piotr-placzek** [kaorun343/vue-property-decorator#341]
```ts
    @Prop({default: this.$t('dialog.title').toString()}) title: string;
```
above syntax causes a compile-time error:
`Default property has no initializer and is not definitely assigned in the constructor.`

```ts
    @Prop()  title = "title";
```
above syntax causes a runtime-time error:
`
vue.runtime.esm.js?2b0e:619 [Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "title"
`

how should i set the property's default value ?

**Comment by stefusilviu** [comment]
The first one should be solved by this (see `!`):
```javascript
@Prop({default: this.$t('dialog.title').toString()})
title!: string;
```

The second one is due to the fact that somewhere in your components's code you assign another value to that prop. You may keep the `title` value in a separate property and `@Watch` the change of the prop. Something like this:

```javascript
@Prop()
title = "title";

localTitle!: string;

@Watch("title")
onTitleChange(val: string): void {
  this.localTitle = val;
}
```
then in your html...
```html
<h1>{{ localTitle }}</h1>
```

**Comment by kaorun343** [comment]
Hi.

Due to the technical problem, it’s needed to initialize default values of props via `default: ` option.
Please read this below.

https://github.com/kaorun343/vue-property-decorator#each-props-default-value-need-to-be-defined-as-same-as-the-example-code-shown-in-above

Thanks.
