### ISSUE TITLE
beforeRouteLeave isn't called

### ISSUE THREAD

**Issue by myalban** [kaorun343/vue-property-decorator#345]
Hi,

First, thanks for this package , it's my favorite 👍 

But I've an issue with route guard and beforeRouteLeave

My component.vue is :

<template>
<div>ok</div>
</template>

`import { Component , Vue, Watch } from "vue-property-decorator";  

@Component({
  components: { 
  },
  beforeRouteLeave(to, from, next) {
    console.log("no way")
    next(false)
  },
})
`

but beforeRouteLeave is never called.

Do you have an idea ?

Thanks,

Best regards,
Alban

**Comment by workkk98** [comment]
In my Opinion, it may be u forgot  to register hook.If use class-component, every function will be one of  methods' property.check calss-component.org

**Comment by kaorun343** [comment]
@myalban 
Please refer to this document.
https://class-component.vuejs.org/guide/additional-hooks.html

**Comment by weitao-Li** [comment]
> @myalban Please refer to this document. https://class-component.vuejs.org/guide/additional-hooks.html Thanks.

Tanks,it great!
