### ISSUE TITLE
@Prop() made type is any

### ISSUE THREAD

**Issue by gongzza** [kaorun343/vue-property-decorator#35]
i used like this:
```
@Prop()
propA: number
```

### Expected behavior
```
props: {
    propA: Number
}
```

### Actually behavior
i captured this at the vue-devtools
![image](https://user-images.githubusercontent.com/6902005/28701935-9594f88c-7394-11e7-8c00-de35bf3ac800.png)

**Comment by lucasctd** [comment]
Mine is creating the properties with the right types. That's interesting.

**Comment by kaorun343** [comment]
@gongzza 

Hi.

Which Vue are you using? production build, or development build?

**Comment by gongzza** [comment]
@kaorun343 Hi. development build.

**Comment by kaorun343** [comment]
@gongzza 

Could you provide a repository that reproduce your issue?

**Comment by gongzza** [comment]
[repo](https://github.com/gongzza/vue-ts-deco-issue.git)
```
$ git clone https://github.com/gongzza/vue-ts-deco-issue.git
$ cd vue-ts-deco-issue && npm install
$ npm run dev
```

<img width="580" alt="2017-07-29 15 27 58" src="https://user-images.githubusercontent.com/6902005/28742728-b38fb21c-7472-11e7-874a-48209892d2a8.png">

**Comment by kaorun343** [comment]
@gongzza 

Thanks.

I found that `emitDecoratorMetadata` isn't added into your `tsconfig.json`.

**Comment by gongzza** [comment]
oh... thank you T.T
