### ISSUE TITLE
Mixins is broken in ts single file

### ISSUE THREAD

**Issue by ysneo** [kaorun343/vue-property-decorator#350]
![image](https://user-images.githubusercontent.com/17615113/99138569-6d7a7f00-266c-11eb-8ec3-555d7f977beb.png)

Mixins is broken in ts single file, It will be a ts error.
![image](https://user-images.githubusercontent.com/17615113/99138591-a0bd0e00-266c-11eb-96bc-824b7e356241.png)
the "mapGl" property is in 'BaseMap', but ts can't figure out.

--- 
But as you can see, When I moved ts code into Vue file. It works.  and **Why not working when move ts in single file?**
![image](https://user-images.githubusercontent.com/17615113/99138794-47ee7500-266e-11eb-8c23-321a337d226c.png)

**Comment by kaorun343** [comment]
@ysneo 
Hi.
`Mixin` function is from `vue-class-component`, so could you ask this question at its repository?
