### ISSUE TITLE
[Vue 3.0] update plan

### ISSUE THREAD

**Issue by kaorun343** [kaorun343/vue-property-decorator#352]
ref #294 

- [x] list all changes https://github.com/kaorun343/vue-property-decorator/blob/next/CHANGELOG.md#v1000-rc1
- [x] create 'next' branch

**Comment by Mikilll94** [comment]
@kaorun343 
Which version of vue-property-decorator will support Vue 3?

**Comment by kaorun343** [comment]
@Mikilll94 Probably v10 (current version is v9)

**Comment by yacan8** [comment]
@kaorun343 
When is the v10 version planned?

**Comment by demons-joker** [comment]
Look forward to v10

**Comment by calebeaires** [comment]
Our team started to migrate the app to the new Vue 3 and class-component 8.0. We made a little lib to do so until vue-property-decorator is ready to go.

https://github.com/calebeaires/vue-decorator

**Comment by softboy99** [comment]
Hi
vue-class-component hase released 8.0 rc1,when we can get this ready? several months past after this opened, there still no change list and next branch

**Comment by Klowes** [comment]
is this project dead?

**Comment by kaorun343** [comment]
Please check this.
https://www.npmjs.com/package/vue-property-decorator/v/10.0.0-rc.1

**Comment by kaorun343** [comment]
I've released RC version, so I'll close this.
