### ISSUE TITLE
@PropSync ignores, and allows deep mutations, without warnings

### ISSUE THREAD

**Issue by zeroinformatique** [kaorun343/vue-property-decorator#357]
**Is your feature request related to a problem? Please describe.**
Vue and VueX have systems to throw warnings when an illegal mutation is performed on a property or a prop. This is a fine way to detect good-practice issues (shortcuts taken by developers).

My team currently takes many of these shortcuts because `@PropSync` doesn't implement these illegal mutation checks.

For example, if I pass a PropSync `user` which contains `{ name: string, languages: string[] }`;
if a component mutates the name or languages directly, it will be allowed. 
The synchronization occurs only if you set the root object : `syncUser = { name, [...languages] }`

**Describe the solution you'd like**
When you pass an object to a `@PropSync`, and if the development mode is enabled, add deep mutation checks and warnings, so the developer can immediately see he's doing something wrong.

**Describe alternatives you've considered**
I wrote a quick and dirty experimental decorator above `@PropSync` to clone and freeze the object. This is hardcore and I have to test it, but it seems to work.

```ts
import CloneTool from "@/tools/CloneTool";
import { PropOptions } from "vue";
import { createDecorator } from "vue-class-component";
import { Constructor, PropSync } from "vue-property-decorator";

type computed = { get: () => any; set: (v: any) => void };

export function PropSyncFreeze(propName: string, options?: PropOptions | Constructor[] | Constructor) {
  if (process.env.NODE_ENV === "development") {
    return function(target: Vue, key: string) {
      // Apply @PropSync alterations
      PropSync(propName, options)(target, key);
      //
      // We overwrite @PropSync's getter to clone and freeze the deep data, making it impossible to cheat Vue
      createDecorator(function(componentOptions, k) {
        (componentOptions.computed![k] as computed).get = function(this: Record<string, any>) {
          if (this[propName] && typeof this[propName] === "object")
            return CloneTool.deepFreeze(CloneTool.deepCopy(this[propName]));
          return this[propName];
        };
      })(target, key);
    };
  }
  return PropSync(propName, options);
}
```

`DeepClone` is just a standard deep cloning of the object.
`DeepFreeze` deep freezes the object to prevent mutations.

**Comment by kaorun343** [comment]
Thanks for your suggestion.
I checked original Vue's behavior. Vue allows updating prop's properties.
This feature seems good, but providing different behavior by `vue-property-decorator` from Vue's official one is not good, I think.
