### ISSUE TITLE
Data Decorator

### ISSUE THREAD

**Issue by lucasctd** [kaorun343/vue-property-decorator#36]
May you create a Data Decorator (annotation)?
If I create a vue  data attribute in my decorated (@Component) class, it will only be build if it has a default value, otherwise it won't.

**Comment by kaorun343** [comment]
@lucasctd 

Could you provide a sample code that illustrates your idea?

**Comment by lucasctd** [comment]
Yes.


```
'import { Component, Prop, Watch, Data } from 'vue-property-decorator';


@Component({
    template: '<div>My Component</div>'
})
export default class MyComponent extends Vue {

   @Prop()
   name: string;
   @Data()
   data: any;
}
```

I guess it will just "looks better". My "problem" is not with the annotation itself. It's all about having (forced) to set a default value for data attribute. If you don't set one, the data attribute will not be created.
Also, is there any way to set a file for the template? ( eg. .vue files).

Thanks.

**Comment by eddow** [comment]
Indeed, the default value is always compulsory.
```
data: ()=> {
  prop1: null,
  prop2: null
}
```
As no `prop3` is defined here, it will not be watched - that is what `data` is for.

Therefore, the best that could be done with the `@Data` decorator is to make it `null` by default for example => it is better I think to just initialise it to `null`.

**Comment by sylvainpolletvillard** [comment]
Same as @eddow, I don"t think it is necessary since all the class fields declared with an initial value are watched. I'm not sure if it works for `undefined` value through
