### ISSUE TITLE
[Vue 3.0] @Component/Vue 在vue-class-component 8.0不存在

### ISSUE THREAD

**Issue by VirensCn** [kaorun343/vue-property-decorator#364]
` warning  in ./node_modules/vue-property-decorator/lib/index.js

"export 'default' (reexported as 'Component') was not found in 'vue-class-component'

 warning  in ./node_modules/vue-property-decorator/lib/index.js

"export 'default' (reexported as 'Vue') was not found in 'vue'`

Vue 3 使用的vue-class-component 8.0+中已经不存在@Component修饰符，现在使用的是@Options

https://github.com/vuejs/vue-class-component/issues/406

**Comment by hsbtr** [comment]
8.0 API has changed some, @ conponent replaced with @ Options, you can look at the https://github.com/vuejs/vue-class-component/issues/406

**Comment by kaorun343** [comment]
@VirensCn 

I've released RC version of vue-proeprty-decorator, which supports Vue 3.
Please check this, thanks.
