### ISSUE TITLE
'vue-property-decorator' has no exported member 'Component'

### ISSUE THREAD

**Issue by GustavoFenilli** [kaorun343/vue-property-decorator#369]
**Describe the bug**
Trying to import vue-property-decorator does not work as it has no export for component.

```
// Module '"vue-property-decorator"' has no exported member 'Component'.
import { Component, Vue } from "vue-property-decorator";
```

**To Reproduce**
1. npm i vue-class-component vue-property-decorator -D
2. Create a .vue file
3. import { Component, Vue } from "vue-property-decorator";
4. Gives the error Module '"vue-property-decorator"' has no exported member 'Component'.

**Expected behavior**
As stated on the documentation it should work by importing Component from the package.

**Screenshots**
![ERROR](https://user-images.githubusercontent.com/14954720/110486294-46d4ce00-80cb-11eb-9f13-cd61dbf52dd7.jpeg)

**Desktop (please complete the following information):**
 - OS: Linux ( PopOS 20.10 )
 - Node Version: 15.11.0
 - NPM Version: 7.6.0
 - Vue Class Component Version: 7.2.6
 - Vue Property Decorator Version: 10.0.0-rc.2

**Comment by kaorun343** [comment]
@GustavoFenilli 
It's my mistake.
I fixed NPM settings (https://docs.npmjs.com/cli/v7/commands/npm-dist-tag), so could try to install `vue-property-decorator` again? You'll download v9.1.2 (latest).

**Comment by GustavoFenilli** [comment]
Thanks for the fast feedback, I will be checking out tomorrow at work and will update here if it works fine.
