### ISSUE TITLE
does not support 'functional' config?

### ISSUE THREAD

**Issue by benleilei** [kaorun343/vue-property-decorator#37]
If i use 'functional:true', there is a error :
Argument of type '{ functional: boolean; }' is not assignable to parameter of type 'VueClass'.
  Object literal may only specify known properties, and 'functional' does not exist in type 'VueClass'.

my code is 

`
import { Vue, Component } from 'vue-property-decorator'

@Component({ functional: true })
class MyFunctionalComponent extends Vue {
    render(h, ctx) {
      let component = ...
      ....
      return h(component, ctx.data, ctx.children)
   }
}
`

**Comment by kaorun343** [comment]
@benleilei

Hi.
Please see this issue.

https://github.com/vuejs/vue-class-component/issues/120
