### ISSUE TITLE
Purpose of @Model and @ModelSync

### ISSUE THREAD

**Issue by Thaval** [kaorun343/vue-property-decorator#371]
Hi, 

I try to understand what these decorators do. I see they are declaring props (I know these, to pass data down to children) and model (that's new). What's the purpose of "@Model" | "model"-property? 
Can the documentation be extended with an explanation and examples (how to use it and what's happening when using it)?

**Comment by kaorun343** [comment]
@Thaval 

`@Model` decorator and `@ModelSync` decorator are based on Vue 2's `model` API. This `model` API allows components to accept `v-model` .
Please check this out for details. https://vuejs.org/v2/api/index.html#model

When using `@Model` decorator, it is required to call `this.$emit()` manually to tell the parent component that value has been changed by the child component. 

However,  `@ModelSync` converts decorated fields to computed property, which has both getter and setter. In the setter function, `this.$emit` is called with correct event name. So, if you use `@ModelSync` , then you don't have to emit `update` events manually.

**Comment by Thaval** [comment]
Alright, thanks for the explanation. Now I got it! So to say, the @Model decorators could be renamed to VModel too, right?
There difference there is the configuration (changing the default property and event for v-model).
