### ISSUE TITLE
[ERROR] Runtime Error with Vue and Component classes of vue-property-decorator package

### ISSUE THREAD

**Issue by angelhdz** [kaorun343/vue-property-decorator#373]
**Describe the bug**
Error in the browser's console when running the Ionic Vue web app demo.

**To Reproduce**
1. Create the Ionic Vue demo project and running the web app.

**Expected behavior**
Running the web app without errors.

**Screenshots**
Screenshots here https://github.com/calebeaires/vue-decorator/issues/3

**Desktop (please complete the following information):**
 - Windows 10 Version	10.0.19042 Build 19042
 - Chrome: 89.0.4389.90 (Official Build) (64-bit)
 - VSCode : 1.54.3
 ```
   "dependencies": {
    "@capacitor/android": "^2.4.7",
    "@capacitor/core": "2.4.7",
    "@ionic/vue": "^5.6.1",
    "@ionic/vue-router": "^5.4.0",
    "core-js": "^3.6.5",
    "vue": "^3.0.0-0",
    "vue-decorator": "^1.1.2",
    "vue-router": "^4.0.0-0"
  },
 "devDependencies": {
    "@babel/plugin-proposal-class-properties": "^7.13.0",
    "@babel/plugin-proposal-decorators": "^7.13.5",
    "@capacitor/cli": "2.4.7",
    "@types/jest": "^24.0.19",
    "@typescript-eslint/eslint-plugin": "^2.33.0",
    "@typescript-eslint/parser": "^2.33.0",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-e2e-cypress": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-typescript": "~4.5.0",
    "@vue/cli-plugin-unit-jest": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0-0",
    "@vue/eslint-config-typescript": "^5.0.2",
    "@vue/test-utils": "^2.0.0-0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0-0",
    "typescript": "~3.9.3",
    "vue-class-component": "^8.0.0-rc.1",
    "vue-jest": "^5.0.0-0"
  }
  ```

**Smartphone (please complete the following information):**

**Additional context**
I tried vue-property-decorator for many days with no success. Until I installed vue-decorator package and used its Vue and Options classes. I want to use vue-property-decorator because all the tutorials I've read us it, I don't want to rely on vue-decorator because it doesn't seem active. More context here https://github.com/calebeaires/vue-decorator/issues/3

**Comment by kaorun343** [comment]
@angelhdz 

In order to use `useRouter`, it should be called at `setup` function.
https://next.router.vuejs.org/api/#userouter
So it means nothing to call the function at `constructor`.

If you use class-style syntax, you can utilize router object via `this.$router`. 
https://next.router.vuejs.org/api/#component-injected-properties

```ts
import { Vue } from 'vue-property-decoratort'
class YourComponent extends Vue {
  yourMethod() {
    this.$router
  }
}
```

Thanks.

**Comment by angelhdz** [comment]
> @angelhdz
> 
> In order to use `useRouter`, it should be called at `setup` function.
> https://next.router.vuejs.org/api/#userouter
> So it means nothing to call the function at `constructor`.
> 
> If you use class-style syntax, you can utilize router object via `this.$router`.
> https://next.router.vuejs.org/api/#component-injected-properties
> 
> ```ts
> import { Vue } from 'vue-property-decoratort'
> class YourComponent extends Vue {
>   yourMethod() {
>     this.$router
>   }
> }
> ```
> 
> Thanks.
Thank you for the quick reply, but I added the router at the end after I got my app working with **vue-decorator** package. So the router is not at fault of causing this error.

**Comment by angelhdz** [comment]
### Update

I removed the router so we don't get confused while trying to solve this issue. This is my code now:

![image](https://user-images.githubusercontent.com/10191085/111949950-f8a2d000-8ab7-11eb-9684-60e5b886307f.png)

**Comment by angelhdz** [comment]
Here using vue-decorator package:

![image](https://user-images.githubusercontent.com/10191085/111950106-37d12100-8ab8-11eb-9f79-de6f43f0bfcb.png)


No errors.

![image](https://user-images.githubusercontent.com/10191085/111950300-72d35480-8ab8-11eb-9ee6-36025a2dc44b.png)


Here using vue-property-decorator package:

![image](https://user-images.githubusercontent.com/10191085/111950076-2b4cc880-8ab8-11eb-846b-5167edf51dc5.png)

Error:
![image](https://user-images.githubusercontent.com/10191085/111950227-60591b00-8ab8-11eb-8c84-a3f75f59d474.png)

**Comment by kaorun343** [comment]
Using `constructor` with `vue-class-component`  is not available.

```ts
class YourComponent extends Vue {
  title = 'Home'
}
```

**Comment by kaorun343** [comment]
https://class-component.vuejs.org/guide/caveats.html#always-use-lifecycle-hooks-instead-of-constructor

**Comment by angelhdz** [comment]
I removed the constructor and the issue persists. I'm using the classes from vue-property-decorator not  from vue-class-component.

I get another error using Component from vue-class-component package: 

![image](https://user-images.githubusercontent.com/10191085/111950822-2e948400-8ab9-11eb-8bd4-9341e8f21d8f.png)

**Comment by kaorun343** [comment]
1. Which version of `vue` , `vue-class-component` and `vue-property-decorator` are you using? If you're using Vue 3, then you need to install `vue-class-component@8-rc`, and `vue-property-decorator@10-rc` . Also, `@Options` decorator should be used.
2. In `setup` function, `this` is not available. Also, `setup` function should be defined at `@Options` decorator.  In your case, `setup` is not needed.

```ts
import { Options, Vue } from 'vue-property-decorator'

@Options({
  components: {
    // child components
  },
  name: 'Home'
})
export default class Home extends Vue {
  public title = 'Home'
}
```

**Comment by angelhdz** [comment]
Already provided all my devDependencies and dependencies of package.json file. All the versions of everything I'm using are listed in the first comment.

The only thing I think I'm missing is version 10-rc of vue-property-decorator. 

Let me try. Thank you.

**Comment by kaorun343** [comment]
> Already provided all my devDependencies and dependencies of package.json file. 
I saw them and I understand that Vue 3 and vue-class-component@8-rc is used.

**Comment by angelhdz** [comment]
### Solved

I installed vue-property-decorator **10.0.0-rc.3** and ran npm install, and now I can get the Options and Vue classes directly from the vue-class-component package. I couldn't unpack/deconstruct them before. I don't know if installing latest vue-property-decorator was the solution, or if npm failed to install version @8-rc of vue-class-component.

So, it's finally **Solved** I guess...

### Last Words
Let me add, that I can use setup method in the class itself and not in Options, and can use the "this" keyword in it.

![image](https://user-images.githubusercontent.com/10191085/111952714-eaef4980-8abb-11eb-8390-bbf469d0fc75.png)

No errors. 😍🎉🙌🤝

![image](https://user-images.githubusercontent.com/10191085/111952788-08241800-8abc-11eb-8592-54ae7967e8dc.png)

Really appreciate your time and help. 

Stay healthy!
