### ISSUE TITLE
In-Component Guards

### ISSUE THREAD

**Issue by CKGrafico** [kaorun343/vue-property-decorator#38]
Are not working? https://router.vuejs.org/en/advanced/navigation-guards.html

**Comment by kaorun343** [comment]
@CKGrafico 

Hi.

Please check this section.

https://github.com/vuejs/vue-class-component#adding-custom-hooks

**Comment by CKGrafico** [comment]
Working with 
```
@Component({
    beforeRouteLeave(route, redirect, next) {
        if (this && this.hasChanges) {
            if (confirm(translate.get('messages.confirm_close'))) {
                next();
            }
            return;
        }
        next()
    }
})
```

I recommend you don't close the issues that fast :)
