### ISSUE TITLE
vue-router hooks are not triggered in child components (v10.0.0-rc.3)

### ISSUE THREAD

**Issue by maxdzin** [kaorun343/vue-property-decorator#395]
**Describe the bug**
The vue-router registered hooks are not triggered in the nested (any level) components. The hooks only triggering for the parent-top components.

**To Reproduce**

1. Define the parent component:
```
// @/views/Welcome.vue
import { Options, Vue } from 'vue-property-decorator'

@Options({
  components: {
    ChildComponent,
  },

  beforeRouteEnter(to, from, next): void {
    console.log('Parent component route enter hook.') // - THIS IS TRIGGERED WELL
    next()
  },
  beforeRouteUpdate(to, from, next): void {
    console.log('Parent component route update hook.') // - THIS IS TRIGGERED WELL
    next()
  },
  beforeRouteLeave(to, from, next): void {
    console.log('Parent component route leave hook.') // - THIS IS TRIGGERED WELL
  },
})
export default class Welcome extends Vue {
}
```
2. Define the child component:
```
// @/components/ChildComponent.vue
import { Options, Vue } from 'vue-property-decorator'

@Options({
  beforeRouteEnter(to, from, next): void {
    console.log('Child component route enter hook.') // - THIS IS NOT TRIGGERED AS EXPECTED
    next()
  },
  beforeRouteUpdate(to, from, next): void {
    console.log('Child component route update hook.') // - THIS IS NOT TRIGGERED AS EXPECTED
    next()
  },
  beforeRouteLeave(to, from, next): void {
    console.log('Child component route leave hook.') // - THIS IS NOT TRIGGERED AS EXPECTED
    next()
  },
})
export default class ChildComponent extends Vue {
}
```
3. Register routes and hooks:
```
// @/main.ts
...
import { Vue } from 'vue-property-decorator'

Vue.registerHooks([
  'beforeRouteEnter',
  'beforeRouteLeave',
  'beforeRouteUpdate',
])

import { createRouter, createWebHistory, RouteRecordRaw } from 'vue-router'

const routes: Array<RouteRecordRaw> = [
  {
    path: '/',
    name: 'Welcome',
    component: () => import('@/views/Welcome.vue'),
  },
]
const router = createRouter({
  history: createWebHistory(),
  routes,
})

...

const app = createApp(App)
  .use(router)

app.mount('#app')
```

I've also tried to register hooks in the component's single file - the same result.

**Expected behavior**
Vue router hooks should work well in any components - parent, child, or even deep nested child.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (20H2 (OS Build 19042.1110))
 - Browser: Chrome, Firefox, Edge
 - Version: 10.0.0-rc.3

**Additional context**
package.json versions:

"vue": "^3.1.5"
"vue-class-component": "^8.0.0-rc.1"
"vue-property-decorator": "^10.0.0-rc.3"
"vue-router": "^4.0.10"
"vite": "^2.4.3"

**Comment by tsiotska** [comment]
You can invoke component navigation hooks only on registered in router components. So register your child as subroute or just use parents hooks

**Comment by maxdzin** [comment]
Yes. It seems so. For some reason, I thought that must work for the child components as well.
@tsiotska thanks for replying!
