### ISSUE TITLE
How to handle "components" option?

### ISSUE THREAD

**Issue by dclovec** [kaorun343/vue-property-decorator#40]
In .vue file, how to decorate the "components" option? I just want to use decorators only.
I have no idea, wish your reply!

**Comment by kaorun343** [comment]
@dclovec 

Hi.

You can use `@Component` decorator.

https://github.com/vuejs/vue-class-component

**Comment by dclovec** [comment]
I know this. But I just want to use decorator only. Other options must and can only use  `vue-class-component` ?

**Comment by kaorun343** [comment]
What `decorator` does it mean?

Also, `vue-property-decorator` is a plugin for `vue-class-compoent`, so we need to use `@Component` when using this library.

**Comment by dclovec** [comment]
I see. Thanks!
