### ISSUE TITLE
VModel is no longer in this library, will it be added back?

### ISSUE THREAD

**Issue by kylehovey** [kaorun343/vue-property-decorator#415]
**Describe the bug**
`VModel` is not exported by this library, despite being in the documentation (Readme).

**To Reproduce**
1. Attempt to `import { VModel } from 'vue-property-decorator';`

**Expected behavior**
VModel is an exported reference from the library.

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Comment by wtlgo** [comment]
What do you mean? It is exported

https://github.com/kaorun343/vue-property-decorator/blob/master/src/index.ts#L18

**Comment by jojomatik** [comment]
> What do you mean? It is exported
> 
> https://github.com/kaorun343/vue-property-decorator/blob/master/src/index.ts#L18

I think he is talking about version 10 of this project. `VModel` has been removed in https://github.com/kaorun343/vue-property-decorator/commit/3d4056e9c1ce7025e37910cb2a91f90377e03468 (branch `next`). 

@kylehovey have you found a suitable workaround/ alternative for this? @kaorun343 what's the reason the property has been removed, the commit message isn't really helpful tbh?

**Comment by jojomatik** [comment]
I've opened an issue (https://github.com/jojomatik/nuxt-3-base/issues/6) in my template repository for a nuxt3 project, as it is one of the blocking issues for release 1.0.0. This might be helpful to take a look at an example @kaorun343. Thank you.

**Comment by Bob426** [comment]
Hello,
Is there any new news about this? Unfortunately I also encountered this problem

**Comment by jojomatik** [comment]
> Hello, Is there any new news about this? Unfortunately I also encountered this problem

I'm not able to provide any input on this at the moment, as I haven't found time to try any alternatives. If you find out anything, I'd like if you'd add your findings to this thread.

**Comment by jojomatik** [comment]
[I've since heard](https://www.thisdot.co/blog/making-sense-of-multiple-v-model-bindings-in-vue-3) that vue 3 allows [multiple `v-model` directives](https://vuejs.org/guide/components/events.html#multiple-v-model-bindings), I'd assume that it has been temporarily disabled to prevent unwanted behaviours and will be re-added to the export as soon as development and testing have caught up with this change.

Is this the case?

**Comment by kaorun343** [comment]
Use `@Model` instead, please.

**Comment by jojomatik** [comment]
> Use `@Model` instead, please.

I tried your advise and after some issues a few days ago, I got it working today with any problems. Anyone interested can see an example implementation in https://github.com/jojomatik/nuxt-3-base/commit/d09e8c6c2e8708b73ea3b61080ab4ea9f3782331. Thanks @kaorun343!

Unfortunately I can't really explain what issues I ran into, as I didn't fully understand them myself and it seemed to have magically fixed itself today, maybe I was just to tired when I tried it out last time. 

I still hope others can learn from and improve upon my solution.

From my point of view, this issue can be closed. At least if the intial question would be answered:
> will it [`@VModel`] be added back?

**Comment by jojomatik** [comment]
I've pushed additional changes in https://github.com/jojomatik/nuxt-3-base/commit/e6f80e5a52aef99a79e4e98656e17e471b7a37aa to improve on my example and fix a few issues. Please consider both changes in conjunction if you try to implement these yourself.
