### ISSUE TITLE
Need to implement vue-router navigation guards

### ISSUE THREAD

**Issue by DKroot** [kaorun343/vue-property-decorator#42]
I'm implementing a `beforeRouteUpdate` vue-router guard. This is not documented in vue-property-decorator and when I ran into issues I wasn't sure the guards are supported.

I had to look up documentation in `vue-class-component`. The guards are working now, but could you document setup for `vue-property-decorator`?

Also, registration in Component has to happen in a component file. Most of global setup I do happens in the main Vue instance file, but this registration doesn't work there.

```
// Register the router hooks
Component.registerHooks([
  "beforeRouteEnter",
  "beforeRouteUpdate",
  "beforeRouteLeave"
]);
```

**Comment by kaorun343** [comment]
@DKroot 

Hi.

This is library just supports using `vue-class-component`, so in my humble opinion, I hope the developers using this look up the document of `vue-class-components`.

Also, `Component.registerHooks()` should be called before importing or defining all components.

```ts
import Component from 'vue-class-component'

Component.registerHooks([
  'beforeRouteEnter',
  'beforeRouteUpdate',
  'beforeRouteLeave'
])

import Child from './child'

@Component({
  components: {
    Child
  }
})
class RootComponent extends Vue {
}
```

**Comment by DKroot** [comment]
Got it. I think the example above would be very valuable in `vue-property-decorator` README.
