### ISSUE TITLE
Using child components breaks props?

### ISSUE THREAD

**Issue by CallumVass** [kaorun343/vue-property-decorator#47]
Hi,

When I try to use a child component, my prop doesn't get populated so I end up with the following error:
```
Property or method "section" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.
Error in render function: "TypeError: Cannot read property 'name' of undefined"
```
With this code:

Parent Template:
`<section-component v-for="section in page.sections" :key="section.id" :section="section">                 </section-component>`
Code:
```
import Vue from 'vue';
import { Component, Prop, Watch } from 'vue-property-decorator';
import { Section } from '../../models/models';

@Component({
    name: 'section-component',
    components: {
        QuestionComponent: require('../question/question.vue')
    }
})
export default class SectionComponent extends Vue {
    @Prop()
    section: Section;
}
```

However, if I remove the components part from Component decorator. My section-component renders but I'm unable to access my question-component:
```
import Vue from 'vue';
import { Component, Prop, Watch } from 'vue-property-decorator';
import { Section } from '../../models/models';

@Component({
    name: 'section-component'
})
export default class SectionComponent extends Vue {
    @Prop()
    section: Section;
}
```

Any ideas on what I can do to resolve this? Thanks

**Comment by kaorun343** [comment]
@CallumVass 

Hi.

How about writing like this below?

```ts
import QuestionComponent from '../question/question.vue'

@Component({
  name: 'section-component',
  components: {
    QuestionComponent
  }
})
export default class SectionComponent extends Vue {
}
```

So as to do so, you need to add this definition into your project.

```ts
declare module '*.vue' {
  import { ComponentOptions } from 'vue'
  var options: ComponentOptions<any>
  export default options
}
```

**Comment by CallumVass** [comment]
Thank you, that worked

**Comment by zongzi531** [comment]
> @CallumVass
> 
> Hi.
> 
> How about writing like this below?
> 
> ```ts
> import QuestionComponent from '../question/question.vue'
> 
> @Component({
>   name: 'section-component',
>   components: {
>     QuestionComponent
>   }
> })
> export default class SectionComponent extends Vue {
> }
> ```
> 
> So as to do so, you need to add this definition into your project.
> 
> ```ts
> declare module '*.vue' {
>   import { ComponentOptions } from 'vue'
>   var options: ComponentOptions<any>
>   export default options
> }
> ```

Thanks, it is work for me.
