### ISSUE TITLE
[proposal] make @prop more concise

### ISSUE THREAD

**Issue by Evertt** [kaorun343/vue-property-decorator#5]
Right now you have this code in the example:

```javascript
@prop(Number)
propA: number;

@prop({
  type: String,
  default: 'default value'
})
propB: string;
```

However, this could be way way more concise I believe. I would like to propose the following:

Since we're using typescript, how about inferring the property-type from the type that's already defined for typescript? And to make it even better, we could also infer the default value from the type definition itself. So that would change the code into the following:

```javascript
@prop propA: number;

@prop propB: string = "default value";
```

What do you think? I would really really like it to be this concise.

While we're at it, I would like to make one more proposition. Props also have a boolean-value for whether or not they are required of course. I would like that to be inferred as well. If no default value has been provided then I think it should be inferred that the prop is required. So in this case `propA` would be a required prop. And if someone really wants propA to not be required, but also not have a default value, then of course they could define it with `null` as the default value.

Let me know what you think.

([see here for inspiration](https://github.com/locoslab/vue-typescript-component))

**Comment by Evertt** [comment]
Hey I'd like to know whether or not you like this idea. Would you like to tell me?

**Comment by kaorun343** [comment]
I apologise for the delay in replying to you.
I like this idea and I decided to write this code.
Thanks for your suggestion.
But it'll take a time...

**Comment by Evertt** [comment]
Awesome, I'm very happy to hear this. Can you give me a rough indication of how long it might take? Like a few days or a few weeks? Just so that I can curb my enthusiasm for a bit. :-)

**Comment by kaorun343** [comment]
about 1~2 weeks

**Comment by kaorun343** [comment]
Currently, the instance properties with initial value are processed by `vue-class-component` and behave as the properties of object that returned from `data()`.  Also, `@prop` cannot access to these initial values. Therefore, we have to define `default` inside its decorator.

On the other hand,  it's possible set `type` automatically. However, `PropOptions.type` supports not only `Constructor`, but also `Constructor[]`. When defining  instance properties as union type like `propA: number | string`  or `propB: number | Person`, `Reflect.getMetadata` returns `Object`.  Then we need to add its correct type (`[Number, String]`, `[Number, Person]`) manually.

**Comment by Evertt** [comment]
> Currently, the instance properties with initial value are processed by `vue-class-component` and behave as the properties of object that returned from `data()`. Also, `@prop` cannot access to these initial values. Therefore, we have to define `default` inside its decorator.

Ah shiiiiiit, that's a big bummer. I'll open an issue at the vue-class-component repo to ask if they'd be willing to change that so that it would work with this feature.

> On the other hand, it's possible set type automatically. However, PropOptions.type supports not only Constructor, but also Constructor[]. When defining instance properties as union type like propA: number | string or propB: number | Person, Reflect.getMetadata returns Object. Then we need to add its correct type ([Number, String], [Number, Person]) manually.

That sounds fair.

**Comment by kaorun343** [comment]
I published a new version that includes this new feature.

**Comment by Evertt** [comment]
Awesome, thank you! I just have one tiny request to add. It would be nice if the `()` wouldn't be necessary if you don't supply any arguments. So `@Prop()` would then become  `@Prop`. Just like `@Component` already has. Would you be willing to add that?

**Comment by Evertt** [comment]
Hmm, actually, I can't get it to work. I have this component:

```vue
<template lang="pug">
  div
    h1 Hello {{name}}!
</template>

<script lang="ts">
@Component
export default class Hello extends Vue {
  @prop() name: string
}
</script>
```

Which I import in another component like so:

```vue
<template lang="pug">
  div
    hello(:name="3")
</template>

<!-- removed some code for brevity -->
```

So as you can see I'm supplying a number when I should be supplying a string. In other words, I should get a warning from Vue. But I don't.... However, I do get a warning when I change my property like so:

```javascript
@prop(String) name: string
```

**Comment by kaorun343** [comment]
The new Prop decorator is in a metadata.ts.

import { Prop } from "vue-property-decorator/lib/metadata"

**Comment by kaorun343** [comment]
I'll remove unnecessary parentheses.

**Comment by kaorun343** [comment]
I’ve changed my mind. I won't remove it because it makes codes dirty.

**Comment by Evertt** [comment]
How do you mean? Do you mean it makes your library more dirty? Or it makes the code of the developer using your library more dirty?

Because if it's the latter then I want to ask you to still make it optional. Because then apparently there's a difference of opinion in what's clean and what's dirty and then I would like to be able to choose which one I prefer. :-)

**Comment by kaorun343** [comment]
former one.
