### ISSUE TITLE
watch question

### ISSUE THREAD

**Issue by Jack85** [kaorun343/vue-property-decorator#51]
would something like 
```
 @Watch('$route.path')
    onChildChanged(val: string, oldVal: string) 
    { //this.$route.
      console.log("watch call "+val);
    }
```

be possible? currently not watched, without immediate, so that watch is just on particular property? just to make the notation short as possible..

**Comment by kaorun343** [comment]
@Jack85 

Sorry for late reply...

Could you ask about this problem, whether you can watch `$route.path`, at Vue's official forum?
If you can get the answer "Yes, you can watch that property", then it will work well that you showed.
