### ISSUE TITLE
Put the returned value of @Emit decorated function to arguments

### ISSUE THREAD

**Issue by hehoo** [kaorun343/vue-property-decorator#53]
Is it a good idea to put the returned value as one of the arguments for $emit()? e.g. 

```javascript
descriptor.value = function emitter(...args: any[]) {
       this.$emit(event || key, ...args, original.apply(this, args));
}
```
Most of time we want to emit the value returned from the function. How do you think?

**Comment by kaorun343** [comment]
ping @sylvainpolletvillard @eddow

**Comment by eddow** [comment]
Hi,

So, what has been done here is to put the argument of the function as the argument of the event.
Also, the return value of the function is used for now to cancel the emission (by returning false)

There is a lot of ways we could do beside with the return value, for instance use it as the event-name if it is a string, as an argument-list if it is an array, etc.
Now, the way it is implemented until now quite fit all the use-cases I personally encountered;

Thinking a bit more theoretically, it seems to me that the @Emit decorator describes an event, not a function that emits an event, and it seems therefore to me that the function signature should be the event signature. (argument list, etc)
Therefore, I don't think that to add a computed argument to the event is something we should do.

imo, of course

**Comment by sylvainpolletvillard** [comment]
I agree with @eddow . When I propose this @Emit decorator, this is how I describe it : 
> It is used to explicitely declare all the custom events a component might emit.

Methods are more helpful than the original String-based API for emit, because it enables autocompletion and parameters declaration with type annotations. This is the main reason I chose a method decorator for this. 

The method body itself, and the `return false` behaviour proposed by @eddow are just additional features, nice to have, but also feasible in other equally simple ways. Actually, in most of my usecases, I leave the @Emit methods body empty simply because I have no need for it. 

Now, putting the return value in the $emit arguments may be problematic for several usecases:
- variable number of arguments: 
```ts
class Child {
   @Emit("selected")
   selectChoices(...choices){}
}

child.$on("selected", function(choices){
   console.log(`You selected ${choices.length} options`)
})

// logs 3 options because `undefined` has been added to arguments
child.selectChoices("apple","banana") 
```

- default parameter value overriding

```ts
class Child {
   @Emit("deleted")
   deleteItem(item){}
}

child.$on("deleted", function(itemToDelete, shouldSyncWithServer = true){
   // shouldSyncWithServer default value has been overridden with `undefined`
})

child.deleteItem("apple")
```

I think keeping the exact same arguments between the @Emit method and the event listener callback is very important to avoid any confusion.

**Comment by hehoo** [comment]
Thanks @sylvainpolletvillard and @eddow for your explanation. 

Most of cases, the emit function to be decorated by @emit would be an empty method.  It is a bit weird from my point of view, isn't it? It forces user to design a method which arguments are the values to be emitted. What I was thinking before seeing the source code of @emit is that the @emit is used to decorate a method and the method's return value will be emitted. There should be no convention that the arguments are the emitted value.  What values to be emitted should be left to user.

**Comment by eddow** [comment]
For example, I ended up with these in my code :
```
	@Emit() select(item) {}
```
I personally find it nice and declarative. Yes, freedom is nice, freedom taste like sugar - but human made typescript after javascript : restriction helps to structure.

Now, we are still able to call `this.$emit('select', myCat, myDog)`, there is no restriction so to speak; it is just that it declares what I intend to emit. And for some, reading a structured code is more helping than the longest API documentation.

If one just needs to emit an event, he has no need of a decorator: he has `this.$emit` for that purpose. - decorators are not a functionality but a structuration. For instance, people wrote efficient Vue code before `vue-property-decorator`, it is the same : decorators don't allow to do, they allow to declare.

> There should be no convention that the arguments are the emitted value.

Well, we are longing for a convention and trying to make one. Really, if we just wanted to emit an event we would have called `this.$emit` like everyone. Conventions are the point of what decorators are about.

**Comment by sylvainpolletvillard** [comment]
I have not much more to say than what @eddow and I already told before. I note that you feel this is weird, but this is highly subjective and you did not address the issues stated above. I think you will get used to it and see the improvement after using it for a while
