### ISSUE TITLE
noImplicitAny: Could not find a declaration file

### ISSUE THREAD

**Issue by qm3ster** [kaorun343/vue-property-decorator#57]
When importing, eg
```ts
import { Component, Prop, Vue } from 'vue-property-decorator'
```
with 
```json
"noImplicitAny": true
```
I get the following error:
```
[tsl] ERROR in /components/Board/Sum.vue.ts(8,38)
      TS7016: Could not find a declaration file for module 'vue-property-decorator'. '/node_modules/vue-property-decorator/lib/vue-property-decorat
or.umd.js' implicitly has an 'any' type.
  Try `npm install @types/vue-property-decorator` if it exists or add a new declaration (.d.ts
) file containing `declare module 'vue-property-decorator';`
```
On the other hand, clicking on the module name in VSCode takes me to `lib/vue-property-decorator.d.ts`

And everything works correctly with `noImplicitAny: false`

Finally, `allowSyntheticDefaultImports` has no effect, although [vuejs/vue-class-component#usage](https://github.com/vuejs/vue-class-component#usage) claims that it needs to be `true`

**Comment by kaorun343** [comment]
@qm3ster 

Sorry for late reply...

Is this problem still unsolved yet?

**Comment by qm3ster** [comment]
Maybe I had a low Vue version.
I will reopen this if it happens again, I am on a very different setup now.

**Comment by bb** [comment]
I had something very similar with `import { uniq, sortBy } from 'lodash';` and the hint with `noImplicitAny` helped for me. Thanks!

But as I am not using Vue at all in that project, it looks to me like **Vue is not related to this issue**. Btw, I had similar issues with other modules not being found (at all), e.g. mobx-react. Which were also solved this way.

Subscribing to this just in case someone finds out the real reason.
