### ISSUE TITLE
Using @Provide and @Inject on Simple Classes Instead of Components

### ISSUE THREAD

**Issue by RehanSaeed** [kaorun343/vue-property-decorator#60]
In theory I can do something like this, according to the documentation:

```
    import { Component, Inject, Provide, Vue } from 'vue-property-decorator'
    
    const s = Symbol('baz')
    
    @Component
    export class MyComponent extends Vue {
      @Provide() foo = 'foo'
      @Provide('bar') baz = 'bar'

      @Inject() foo: string
      @Inject('bar') bar: string
      @Inject(s) baz: string
    }
```

However, what if I want to use `@Provide` and `@Inject` on a class that is not a component? For example, if I have `ComponentA` that depends on `ServiceA` that depends on `ServiceB`. How can i set this up?

**Comment by CmdrShepardsPie** [comment]
@Provide and @Inject are just decorators to wrap the Class Properties into the Vue implementation for Provide and Inject, and Vue runs that implementation when it creates the Component.

If you use the decorators on a class that is not a Vue Component, the decorators would do the same thing to the properties (wrap them as their Vue implementation) but if Vue isn't creating it, nothing will run that implementation.

If you need dependency injection outside of Vue, I highly recommend Inversify!

https://blog.kloud.com.au/2017/03/22/dependency-injection-in-vuejs-app-with-typescript/
