### ISSUE TITLE
Warnings inside .ts files

### ISSUE THREAD

**Issue by schoening** [kaorun343/vue-property-decorator#61]
I took the *<script lang="ts">* portion of *MyComponent.vue* and pasted it into a *.ts* file:
![image](https://user-images.githubusercontent.com/1976060/32232322-18161756-be58-11e7-9460-a40a78f002a9.png)

I get the following errors:

![image](https://user-images.githubusercontent.com/1976060/32232379-2ecf1952-be58-11e7-8497-3d3f7a6c2048.png)

**Comment by schoening** [comment]
I renamed the title because the files do actually compile, it is the editor that is giving me warnings. I am now unsure if this is because of *vue-property-decorator* at this point..

**Comment by kaorun343** [comment]
@schoening 

Hi.

Could check the issues at `vue-class-component` page ?

**Comment by schoening** [comment]
You were right, sorry about that..

https://github.com/vuejs/vue-class-component/issues/176

I reverted back to TypeScript 2.5.1 and it is working correctly.
