### ISSUE TITLE
Using this keyword in Prop validator

### ISSUE THREAD

**Issue by RehanSaeed** [kaorun343/vue-property-decorator#65]
I'm unable to use the `this` keyword inside a `@Prop` validator. Here is an example of what I'm trying to do:

```
  @Prop({
    default: 0,
    type: Number,
    validator: (x) => x >= this.minValue && x <= this.maxValue,
  })
  public value: number;

  @Prop({
    default: 100,
    type: Number,
  })
  public maxValue: number;

  @Prop({
    default: 0,
    type: Number,
  })
  public minValue: number;
```

The error I get from TypeScript is:

> 'this' implicitly has type 'any' because it does not have a type annotation.

**Comment by rndmerle** [comment]
You could try `(this as any).minValue`

**Comment by kaorun343** [comment]
@RehanSaeed 

Hi.

Please write like this below.

```ts
@Component
class YourComponent extends Vue {
  @Prop({
    default: 0,
    validator(this: YourComponent, x) { return x >= this.minValue && x <= this.maxValue }
  })
  public value: number
}

**Comment by RehanSaeed** [comment]
That doesn't seem to work, `this` is coming back as `undefined`. I'm not using an arrow function.

**Comment by kaorun343** [comment]
@RehanSaeed 

I don't know whether we can use `this` inside `validator` function.

**Comment by RehanSaeed** [comment]
I think this is a bug, `this` should resolve to the current instance of the component. It just needs to be bound correctly.

**Comment by kaorun343** [comment]
Hi.

I apologize to you for late reply.
I found that in `validator` functions, `this` is not instance of `Vue`.
