### ISSUE TITLE
Maybe @Prop don't support ES file.

### ISSUE THREAD

**Issue by Emiya0306** [kaorun343/vue-property-decorator#67]
This is the example code.

```html
<!-- Component: vSidebar.vue -->
<template>
  <aside class="vSidebar">
    {{test}}
  </aside>
</template>

<script>
import { Component, Vue, Prop } from 'vue-property-decorator';

@Component
class vSidebar extends Vue {
  @Prop()
  test;

  mounted() {
    console.log(this)
  }
}

export default vSidebar;
</script>
```

```html
<!-- Parent: App.vue -->
<template>
  <div class="App">
    <template v-if="user">
      <v-header />
      <v-sidebar :test="test" />
    </template>
  </div>
</template>

<script>
import { Component, Vue, Watch } from 'vue-property-decorator';

@Component
class App extends Vue {
  test = '123'

  get user() {
    return this.$store.state.user.loginUser;
  }

  @Watch('user')
  onUserChange() {
    if(this.user) {
      this.$router.push('dashboard');
    } else {
      this.$router.push('signin');
    }
  }
}

export default App;
</script>
```
I'm sure `@Watch` is working, but `@Prop` not. I got `vue.esm.js:571 [Vue warn]: Property or method "test" is not defined on the instance but referenced during render.` and `this.test` in vSidebar is undefined when mounted hook emitted. If I use @Component({props}), it works.

**Comment by hworld** [comment]
Getting a similar error but it's saying something weird about the prop can't be modified even though the value I'm modifying isn't a prop... THis is the file: https://github.com/gamejolt/frontend-lib/blob/master/components/form-vue/control/base.ts

When I modify "value" it's complaining that it's a prop, even though the prop is "rules". When I do the "fix" above it fixes it.

**Comment by hworld** [comment]
Seems related to this change, actually: https://github.com/vuejs/vue-class-component/commit/e9f0e6b78be13b8fecbae466171b8345e58e6f09 When I downgraded vue-class-component to 6.0.0 again it fixed it.

**Comment by Emiya0306** [comment]
@hworld Sorry for late response. I'm sure that `vue-class-component` in my code is v6.0.0, but it is not work.

vue: 2.5.2
babel-loader: 7.1.2
vue-loader: 13.3.0
vue-class-component: v6.0.0
vue-property-decorator: v6.0.0

**Comment by kaorun343** [comment]
Hi, everyone.

I apologize you for late reply.

I also mentioned this problem and what I found is that when target (TypeScript's target) is `ES2015` it works well, but when `ES5`, it doesn't.

**Comment by Emiya0306** [comment]
Yeah, Thanks for reply! I think it is compiler's problem, maybe the compiler ignored the properties of class without initialized value after compiled. I test it in babel, it is same. It is understandable that vue-property-decorator will not working without class property.

**Comment by foxbunny** [comment]
@kakenbok See #136 where this has already been discussed.

**Comment by dmitrykurmanov** [comment]
@kaorun343 I have the same error and I use `"target": "es5",`. Could you please give me an advise about it?

**Comment by Emiya0306** [comment]
@foxbunny FYI

> @prop currently needs to have a default value present. Otherwise it gets ignored.

What @kakenbok say is the default value, not default props type. Because of no default value, the babel will ignore compile the `@Prop`, so `@Prop` is not working.

But I don't care in my project. Just the opposite that I define new code style. You can see [here](https://github.com/kaorun343/vue-property-decorator/commit/2f66bfd8309efcf004af1a88953da4a7e48dbe01#r30194448).

@dmitrykurmanov Hey, my advise is the [link](https://github.com/kaorun343/vue-property-decorator/commit/2f66bfd8309efcf004af1a88953da4a7e48dbe01#r30194448) above. If you really care about this, I think it should add default value in `vue-property-decorator`.

**Comment by dmitrykurmanov** [comment]
@Emiya0306 thank you for the response and for the suggestion. But I use typescript. Here an example:

```ts
import { Vue, Component, Prop } from "vue-property-decorator";

@Component
export class Row extends Vue {
  @Prop() row!: any; // without exclamation sign it doesn't work too
  ...
}
```

I used webpack2 and typescript 2.6.1 before and I want to udpate webpack and typescript version to the latest. If you want I can give a link to the repo. It is public in the Github.

Thanks again.

**Comment by kaorun343** [comment]
@Emiya0306 

Hi.

https://github.com/Microsoft/TypeScript/pull/20075

Here's the reason why the exclamation mark is needed. The feature is introduced since TS 2.7.
