### ISSUE TITLE
Prop type any throws Vue warn

### ISSUE THREAD

**Issue by hoppities** [kaorun343/vue-property-decorator#69]
I'm receiving the following error:

`[Vue warn]: Invalid prop: type check failed for prop "value". Expected Object, got Number.`

    @Component({
        name: 'ax-select'
    })
    export default class AXSelect extends Vue {

        @Prop() classes: string;
        @Prop() items: Array<any>;
        @Prop() label: string;
        @Prop() value: any;
    }

**Comment by kaorun343** [comment]
@hoppities 

Hi.

Currently, I use `reflect-metadata` so as not to write like this `@Prop(String) classes: string`. However, when the type of a property is `null`, the prop type is going to be `Object`.

Also, the current type definition of Vue.js doesn't supports applying `null` to the `type` property in prop definitions.

**Comment by aweiu** [comment]
@hoppities 
I met this problem, too.You can do this:
```
@Prop()
value: undefined;
```

**Comment by DrSensor** [comment]
I also have a similar problem. Here is my use case:
`[Vue warn]: Invalid prop: type check failed for prop "hideRoute". Expected Object, got String.`
```js
  @Prop({ default: '' })
  hideRoute: string | string[]

  get router() {
    return filter(get(this.$router, 'options.routes'), 'meta.icon').map(o => {
      .
      .
      if (!this.hideRoute.includes(o.alias) && !this.hideRoute.includes(o.name)) {
        return Object.assign(route, meta)
      }
    })
  }
```
using
```js
hideRoute: string | string[] | undefined
```
is not an option for me because `includes()`

**Comment by grzegorztomasiak** [comment]
@DrSensor can't you just make

```ts
  @Prop({ 'default': () => [] })
  hideRoute: Array<string>
```

**Comment by DrSensor** [comment]
@grzegorztomasiak in the end, I declare it like this
```
  @Prop({ default: '', type: [String, Array] })
  hideRoute: string | string[]
```
> Although its bit awkward to use `type: [String, Array]` 
while there is typescript annotation `string | string[]`

**Comment by kaorun343** [comment]
Please use the new version v7.0.0.
