### ISSUE TITLE
How to render Component in SFC

### ISSUE THREAD

**Issue by anymost** [kaorun343/vue-property-decorator#72]
I want to know when import a Component in SFC using vue-property-decorator，how  to render this component in SFC

**Comment by kaorun343** [comment]
@anymost 

Hi.

There's no special techniques to do so.
Please check this file.

https://github.com/vuejs/vue-class-component/blob/master/example/World.tsx

**Comment by kaorun343** [comment]
@anymost 

Hi.

How about this code?

```ts
import { Component, Vue } from 'vue-property-decorator'
import ChildComponent from './ChildComponent.vue'

@Component({
  components: { ChildComponent }
})
export default YourComponent extends Vue {
}
```

**Comment by killbom** [comment]
I also had issues with this, but your example works for me.

Is this documented anywhere?

**Comment by anymost** [comment]
Just Fine, thank you
