### ISSUE TITLE
Changelog is missing

### ISSUE THREAD

**Issue by raffomania** [kaorun343/vue-property-decorator#73]
I'd like to update to 6.0.0 but am afraid of breaking my app. Where can I find a list of changes between versions?

**Comment by raffomania** [comment]
I'm sorry, I still can't find the changelog. I must have overseen it?

**Comment by kaorun343** [comment]
I've just added it......

**Comment by raffomania** [comment]
Where do I find it? I looked in the README and for a `CHANGELOG` file, but found none.

**Comment by kaorun343** [comment]
https://github.com/kaorun343/vue-property-decorator/releases

Could you check this page?

**Comment by m4ss1m0g** [comment]
Current version is 7.3.0 but on [changelog ](https://github.com/kaorun343/vue-property-decorator/releases) there is until 7.0.0

**Comment by kaorun343** [comment]
@raffomania 

Hi. I've just added it......

**Comment by GodofHope** [comment]
And sitll missing recent changelogs

**Comment by GodofHope** [comment]
Wow，thanks

**Comment by service-paradis** [comment]
Can you update the changelog for 8.4.0?

Thanks a lot for your work! :)
