### ISSUE TITLE
@Watch not working with objects

### ISSUE THREAD

**Issue by ivanromakh** [kaorun343/vue-property-decorator#75]
I have problem watch is working with objects very intresting like something wokring sometimes not but If I make it in vue it worked always event without deep attribute. Maybe this is becouse of name of function like onChildChanged() how I need to name function?
with strings and numbers it worked fine.

Changed object I get from other component as v-model="findedObject"

**Comment by ivanromakh** [comment]
I used this.$emit('event', object),  and now I don`t need watch but maybe it will be needed someone else

**Comment by ivanromakh** [comment]
I used few hour on it so if this is n`t worked used please remove it from readme, thanks

**Comment by jsonberry** [comment]
The Watch decorator is working properly for me, without and without deeply watching an object. Here's a working example: https://github.com/jsonberry/vue-typescript-examples/blob/master/src/components/watch/WatchExample.vue#L64

**Comment by PeterParker** [comment]
Unfortunately I'm seeing the same issue as @ivanromakh.

@jsonberry, I copy-and-pasted your example into my project and was not able to see the `@Watch` decorator work for `"anObj.foo"`, but it seemed to work fine for `"count"`.

I'm new to JS, TS and Vue, but would be more than willing to try and help identify this issue.

Some presumably-relevant entries from my `package.json` file:

```json
"dependencies": {
    ...
    "vue": "^2.5.2",
    "vue-property-decorator": "^6.0.0",
    ...
}
```

Any thoughts on what I might try to get this to work?

**Comment by PeterParker** [comment]
I experimented with decorating the watched object with the `@Prop` decorator and it seems to "see" the change happen.  Unfortunately, Vue issues a warning about mutating props directly and advises against it.

**Comment by jsonberry** [comment]
@PeterParker Hmm, not sure. Let's look into it, can you make an issue over on that repo and I can dig into it later? https://github.com/jsonberry/vue-typescript-examples/issues

**Comment by jsonberry** [comment]
@PeterParker
@ivanromakh 

Are you able to share any more code examples or a repo? I'm unable to reproduce this behavior. The Watch decorator is working properly for me in this example: https://github.com/jsonberry/vue-typescript-examples/blob/master/src/components/watch/WatchExample.vue#L64

Maybe try cloning the example repo and playing around with it?

**Comment by PeterParker** [comment]
@jsonberry - I started up your example and it works without any issues.

But now I think I've discovered what the issue is -- the watched variable must not start out life as being `undefined`.  My own code works once I actually initialise it with a real object.  (And when I copy-and-pasted your example into my code I obviously didn't make a very good job of it...)

I'm sorry for wasting your time.

**Comment by jsonberry** [comment]
Oh! So, in order for the component properties to work inside Vue’s reactivity system, they need to be declared. They can’t be undefined as you mentioned, but you can declare them first as null, or as an empty object, things of that nature.

Good catch!

**Comment by r1m** [comment]
This may be link to the vue-class-component : [Undefined is not reactive](https://github.com/vuejs/vue-class-component#undefined-will-not-be-reactive)
You need to initialize with ```null```

**Comment by ivanromakh** [comment]
I solve it by clearing objects or timeout events

**Comment by Virgil-N** [comment]
You should set computed method for it. I use it well.
