### ISSUE TITLE
decorators working except for @watch

### ISSUE THREAD

**Issue by hmexx** [kaorun343/vue-property-decorator#76]
I'm using a lot of the decorators fine, but when I try @watch I get the following error: "Unable to resolve signature of method decorator..."

Any ideas?

```typescript

@V.Component({
   name: "dateslotpicker"
})
import * as V from "vue-property-decorator";

export default class cDateSlotPicker extends V.Vue {
today = true;

@V.Watch('today')
  onDayChange(val:boolean, oldVal:boolean) {
  }
}
```

**Comment by jsonberry** [comment]
That's weird. I'm using the Watch decorator, and it's working. Here's an example: https://github.com/jsonberry/vue-typescript-examples/blob/master/src/components/watch/WatchExample.vue

**Comment by trekze** [comment]
For now I'm just adding a  // @ts-ignore in front of the watch decorator and it's working correctly. Not sure why my typescript compiler is not happy but it solves the issue until I have time to look into it further.

e.g.

**Comment by hmexx** [comment]
Hi @kaorun343 

At some point during the last 5 months, the error stopped appearing. Not sure which dependency update (typescript compiler?) was linked to the resolution, but I don't need to ignore the lines anymore.
