### ISSUE TITLE
How to use filert with vue-property-decorator

### ISSUE THREAD

**Issue by aibrahim3546** [kaorun343/vue-property-decorator#79]
usually in normal vuejs we declare filter like this:

filter: {
    trim(){
        // some code here
     }
}

how to do it with typescript vue-property-decorator

**Comment by kaorun343** [comment]
@aibrahim3546 

Hi.

like this below.

```ts
import { Component, Vue } from 'vue-property-decorator'

@Component({
  filters: { trim() { // some code here } }
})
class YourComponent extends Vue {
}
```

**Comment by aibrahim3546** [comment]
Thank you, it works prefectly 👯‍♂️

**Comment by xyqiao** [comment]
great
