### ISSUE TITLE
Explanation

### ISSUE THREAD

**Issue by davidm-public** [kaorun343/vue-property-decorator#80]
Hi, have been using `vue-property-decorator` for some time, awesome.
However, have only been using these decorators: 
  - @Watch
  - @Component 

Do you have a good pointer to an explanation / examples of these ?: 
  - @Emit
  - @Inject
  - @Model
  - @Prop
  - @Provide

**Comment by denimaaark** [comment]
I agree, please add some examples.

**Comment by jsonberry** [comment]
Hey all,

I've been slowly working on a Vue + TypeScript example repo. Hope this helps: https://github.com/jsonberry/vue-typescript-examples

Would love PRs and please open an issue there if you find anything weird!

@Provide and @Inject example: https://github.com/jsonberry/vue-typescript-examples/tree/master/src/components/dependency-injection

@Emit example: https://github.com/jsonberry/vue-typescript-examples/tree/master/src/components/components-event-emitting

@Prop example: https://github.com/jsonberry/vue-typescript-examples/tree/master/src/components/passing-properties-down

@Model example: https://github.com/jsonberry/vue-typescript-examples/tree/master/src/components/forms

Pro tip: best to clone the repo, install deps, and then poke around in it 👍

**Comment by peterchealse** [comment]
cool

**Comment by davidm-public** [comment]
@jsonberry Very nice examples, thanks!!
