### ISSUE TITLE
Help with @Model @Provide @Inject

### ISSUE THREAD

**Issue by mailok** [kaorun343/vue-property-decorator#82]
I was looking for documentation of Vuejs and I find no reference to this @Model @Provide @Inject within components. someone could tell me where I find the utility of using @Model, @Provide and @Inject in Vuejs?

**Comment by sebastienrocks** [comment]
Hi @mailok 

v-model: https://vuejs.org/v2/api/#v-model
provide / inject: https://vuejs.org/v2/api/#provide-inject

I'm supposing you were looking at the basic guide for VueJS. If you look in the actual API you will have a much more in-depth _vue_.
