### ISSUE TITLE
No type reflection with transpileOnly:true on ts-loader 

### ISSUE THREAD

**Issue by rndmerle** [kaorun343/vue-property-decorator#83]
Hi.

Maybe it's totally to be expected but I might as well ask:
When I set `transpileOnly` at true in ts-loader options it seems the type reflection is no longer working for "complex" types.
With:
```
@Prop() menuTree: MenuItem[];
@Prop() callBack: Function;
@Prop() disabled: boolean;
```
I get Vue warns at run time:
```
[Vue warn]: Invalid prop: type check failed for prop "menuTree". Expected Object, got Array.
[Vue warn]: Invalid prop: type check failed for prop "callBack". Expected Object, got Function.
```

With transpileOnly at false everything was fine.

Any idea?

**Comment by teslor** [comment]
I'm using vue-cli 3 (transpileOnly is set to true by default) and have the same issue. Could anyone comment? Is any way to avoid this? Thanks.

**Comment by kaorun343** [comment]
Could you try the new version, `7.0.0` ?

**Comment by rndmerle** [comment]
Thanks for the update.
Yea warnings are gone.
But indeed since there is no longer type reflection all the primitive props like booleans are no longer working. I can't bear thinking about double-typing all the props :(

**Comment by kaorun343** [comment]
Yes, type reflection has been removed because I stopped using `reflect-metadata`.

There are the issues reported that is caused by type reflection. 
This is the reason why I brought this breaking change.
