### ISSUE TITLE
Computed attributes

### ISSUE THREAD

**Issue by brunosiqueira** [kaorun343/vue-property-decorator#85]
How can I use computed attributes with decorators?
Thanks!

**Comment by ninjascant** [comment]
As mentioned in [this tutorial](https://alligator.io/vuejs/typescript-class-components/), computed properties are implemented in vue-property-decorator as ES6 getters:
```javascript
@Component
export default class App extends Vue {
  get myComputedProp() {
    return Math.random()
  }
}
```
Which is equal to this plain Vue syntax:
```javascript
export default {
  computed: {
    myComputedProp() {
      return Math.random()
    }
  }
}
```

**Comment by barakbd-bluevine** [comment]
What about setters?
I could not find an example of that

**Comment by kaorun343** [comment]
@barakbd-bluevine 

Hi.

```ts
@Component
export default class App extends Vue {
  set myComputedProp(value: any) {
    console.log(value)
  }
}
```

**Comment by awacode21** [comment]
What about two-way computed properties (with get and set) in TypeScript. I absolutely do not find any example on this

**Comment by GeniaT** [comment]
Would be great to add computed attributes examples to the documentation.

**Comment by kaorun343** [comment]
Converting from getters / setters to computed properties is provided by `vue-class-component`. Please ask to the repository.

```ts
@Component
class YourComponent extends Vue {
  get value() {
    return `${this.firstname} ${this.lastname}`
  }

  set value(fullname: string) {
    const [firstname, lastname] = fullname.split(' ')
    this.firstname = firstname
    this.lastname = lastname
  }
}
```

**Comment by kaorun343** [comment]
It'll be supported if the Vue itself does.
