### ISSUE TITLE
Support :prop.sync and enhance model sync

### ISSUE THREAD

**Issue by DrSensor** [kaorun343/vue-property-decorator#86]
Every time I want to implement Dialog Component I need to make getter/setter (computed properties) for that.

```ts
@Component
export default class MyDialog extends Vue {
  @Model() dialog: boolean

  get open() {
    return this.dialog
  }
  set open(value: boolean) {
    this.$emit('dialog', value)
  }
}
```

I'm proposing decorator `@Sync`, `@PropSync`, and/or `@ModelSync` to make it easier

---
### Decorator
`@Sync(eventAndProp?: String)`

#### usage 
```ts
@Sync('dialog') open: boolean
```

will produce something like

```ts
  get open() {
    return this.dialog
  }
  set open(value: boolean) {
    this.$emit('dialog', value)
    // or
    this.$emit('update:dialog', value)
  }
```

---
### Decorator
`@PropSync(event?: String, options?: (PropOptions | Constructor[] | Constructor))`

#### usage 
```ts
@PropSync() open: boolean
```

will produce something like

```ts
  @Prop() open: boolean
// I can't find a way to use setter instead of emit
  open(value: boolean) {
    this.$emit('update:open', value)
  }
```
> https://vuejs.org/v2/guide/components.html#sync-Modifier

---
### Decorator
`@ModelSync(event?: String, options?: (PropOptions | Constructor[] | Constructor))`

#### usage 
```ts
@ModelSync() open: boolean
```

will produce something like

```ts
// because when using model it only use `v-model`, not like prop `:$_open.sync=`
  @Model() $_open: boolean
  get open() {
    return this.$_open
  }
  open(value: boolean) {
    this.$emit('open', value) // notice that there is no 'update:'
  }
```

**Comment by sotaan** [comment]
Is there any workaround at least, I really need to use `.sync` in some cases
