### ISSUE TITLE
@Emit:  How to pass values ?

### ISSUE THREAD

**Issue by DevinWell1ee** [kaorun343/vue-property-decorator#89]
@Emit('change')
doSth () {}

In this way, how to pass values ?

In the Vue.js is like 'this.$emit('change', {a: 1})'
i want to pass the '{a: 1}' with @Emit

**Comment by nitesh-13** [comment]
You need to pass the arguments to the function you are using with **@Emit** annotation.
`
@Prop() testObject = {a: 1};
@Emit('change')
doSth(testObject ) { }
`

Something like this will work for you.

**Comment by herrdu** [comment]
@nitesh-13 
if I do like you said , how can i get the  "event" Object ?

**Comment by nitesh-13** [comment]
@herrdu 
You can use `$event` if you are calling this function from any event in HTML element
e.g.
So Your HTML would look something like this
`
<div :click="doSth($event, testObject)">Click me</div>
`
and your JS will look like this
`
@Prop() testObject = {a: 1};

@Emit('change')
doSth(event, testObject ) { }
`

or if you want to make some changes after click then call some other function
`
<div :click="test($event)">Click me</div>


@Prop() testObject = {a: 1};

test(event) {
    testObject = {b : 1};
    doSth(testObject);
}

@Emit('change')
doSth(testObject ) { }
`

@DevinWell1ee and @herrdu 
Please check the sample examples shown [here](https://github.com/kaorun343/vue-property-decorator) properly and checkout the implementation for `Emit` annotation.

**Comment by nitesh-13** [comment]
I think $event should be passed explicitly
