### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by AndreasBackx** [kaorun343/vue-property-decorator#90]
Could some proper documentation page be added to the project? There'd be no need for issues like #80 and it could give new users of the library an actual explanation of how the decorators work. Currently the very brief example in the README doesn't make everything clear and I'm still stuck on a lot of stuff that could just be cleared up if this project were documented.

**Comment by yordis** [comment]
I would like to know in the docs what is the differences between using `@Prop({ default: "something" })` and initializing the default value as `myProp = "something"`

**Comment by itshizhan** [comment]
yeh, it's too confused!  

`@Prop({ default: "something" }) propA `  defined a prop  `propA`,that is derived from parent component

`myProp = "something"` just defined a local data  `myProp`

in fact, you can try:
 ```typescript
@Prop({ default: 'default value' })
  propB!: string 
```

**Comment by yordis** [comment]
@itshizhan I updated the code snippet because I made a mistake in the second block, I meant to be using Prop all the time.
