### ISSUE TITLE
use prop error

### ISSUE THREAD

**Issue by 33033624** [kaorun343/vue-property-decorator#91]
![image](https://user-images.githubusercontent.com/19551550/38089623-b56a6c32-3392-11e8-8936-ade60df7d4f4.png)

**Comment by kaorun343** [comment]
@33033624 

I apologize to you for late reply.

Have you solved your problem?
This library is targeted for TypeScript, not JavaScript, and the error you showed is caused because of TS's syntax is used in JS.
