### ISSUE TITLE
@Model — how to set a defalut value

### ISSUE THREAD

**Issue by herrdu** [kaorun343/vue-property-decorator#92]
<pre>
<script lang="ts">
  import {Component,Prop,Vue,Emit,Model} from "nuxt-property-decorator"
 
  @Component
  export default class extends Vue {
    @Model('click')
    value:string

    status:string = this.value
    
    onClick (): void {
      console.log(this.value)
      if (!this.status) {
        this.status = 'asc';
      } else if (this.status == 'asc') {
        this.status = 'desc';
      } else if (this.status == 'desc') {
        this.status = '';
      }
      this.$emit('click', this.status);
    }
  }
</script>
</pre>

I have a 'value ' prop upder  @Model, but how can I set a default value for it?    

Thank you~

**Comment by agentschmitt** [comment]
Should work with:
```
    @Model('click', { default: 'value' })
    value:string
```

**Comment by herrdu** [comment]
@agentschmitt   
got it. Thank you!
