### ISSUE TITLE
How to use/pass props from parent to child?

### ISSUE THREAD

**Issue by goors** [kaorun343/vue-property-decorator#93]
I have in my vuejs bunch of function that i am passing from parent to child like:

`props:["onComplete","changeSubCategory","set_construction_year","validate_form"]`

how to do this with `@Prop`?

**Comment by kaorun343** [comment]
@goors 

Try this below, please.

```typescript
@Component
class YourComponent extends Vue {
  @Prop onComplete: Function
  @Prop changeSubCategory: Function
  @Prop set_construction_year: Function
  @Prop validate_form: Function
}
```
