### ISSUE TITLE
using @Emit to pass data to parent

### ISSUE THREAD

**Issue by rcholic** [kaorun343/vue-property-decorator#94]
I don't see in the example or documentation about how to pass data from child to parent component.
I tried this, but it does not work: `@Emit('reset', this.dataObject, this.isSelected);`

I don't find a way to pass more than one data objects using @Emit decorator.

**Comment by rico** [comment]
@rcholic it's explained in another issue - the data passed is equivalent to the method parameters.

e.g. in the child component:

     @Emit('selected')
     selected (item : string) {}

You will get the item in the handler in the parent component:

    <component @selected="handleSelected"/>

    handleSelected(item) { ... }
