### ISSUE TITLE
I'd like to remove a dependence on 'reflect-metadata' 

### ISSUE THREAD

**Issue by kaorun343** [kaorun343/vue-property-decorator#97]
What do you think about this?

**Comment by mbriggs** [comment]
I was actually browsing the issues to see if this was possible. I would rather explicitly add decorators for computed properties and data.

**Comment by kaorun343** [comment]
There’s no plan to add such decorators because the feature to define such properties implicitly are provided by `vue-class-component`.

**Comment by championswimmer** [comment]
Any particular reason why this happened ?
